Feature/maroon 319 coord system
GamesResearchTUG/Maroon pull request #372
Opened 2021-10-22 14:57 UTC by dpdsw

closes #319

2021-11-29 12:05 UTC, michaelholly requested changes

2021-11-29 12:05 UTC, michaelholly commented on unity/Assets/Maroon/reusablePrefabs/CoordSystem/SystemChangeHandler.cs
> + * Currently doing nothing
Do we still need this script?
If not, please remove it.

2021-11-29 12:05 UTC, michaelholly commented on unity/Assets/Maroon/reusablePrefabs/CoordSystem/Scripts/Runtime/CoordSystem.cs
> +        public Vector3 GetPositionInWorldSpace(Vector3 localSpacePosition, Unit[] respectiveUnits)
Can we make the respectiveUnity parameter optional?
e.g. GetPositionInWorldSpace(Vector3 localSpacePosition, Unit[] respectiveUnits =null)
respectiveUnits ??= new[] { Unit.m, Unit.m, Unit.m };

2021-11-29 12:05 UTC, michaelholly commented on unity/Assets/Maroon/reusablePrefabs/CoordSystem/Scripts/Runtime/CoordSystemManager.cs
> +        public Vector3 GetWorldLengthsOfDirection(bool positive)
Can we use C# proporties for this?
e.g. 
Vector3 PositiveWorldLength => new Vector3(.....);
Vector3 NegativeWorldLength => new Vector3(...);

2021-11-29 12:05 UTC, michaelholly commented on unity/Assets/Maroon/reusablePrefabs/CoordSystem/Scripts/Runtime/CoordSystemManager.cs
> +        private int FindInList(Axis direction)
Why do we need this function? Just use linq functions.
e.g.  _axisList.Find(axis => axis.AxisID == Axis.X);

2021-11-29 12:05 UTC, michaelholly commented on unity/Assets/Maroon/reusablePrefabs/CoordSystem/Scripts/Runtime/CoordSystemManager.cs
> +            _axisDictionary = DictionaryFromAxisList();
Why not just:
foreach (var axis in _axisList)
  _axisDictionary[axis.AxisID] = axis;

2021-11-29 12:05 UTC, michaelholly commented on unity/Assets/Maroon/reusablePrefabs/CoordSystem/Scripts/Editor/CoordAxisEditor.cs
> +            EditorGUILayout.PropertyField(_worldLength);
Can we use a slider for this property?

2021-11-29 12:05 UTC, michaelholly commented on unity/Assets/Maroon/reusablePrefabs/CoordSystem/Scripts/Editor/CoordAxisEditor.cs
> +            EditorGUILayout.PropertyField(_axisSubdivision);
Can we use a slider for this property? And allow only integer numbers?

2021-11-29 12:05 UTC, michaelholly commented on unity/Assets/Maroon/reusablePrefabs/CoordSystem/Scripts/Editor/CoordAxisEditor.cs
> +            EditorGUILayout.PropertyField(_localLength);
Can we use a slider for this property?

2021-11-29 12:05 UTC, michaelholly commented on unity/Assets/Maroon/reusablePrefabs/CoordSystem/Scripts/Editor/CoordAxisEditor.cs
> +            EditorGUI.BeginChangeCheck();
one BeginChangeCheck at the start and one EndChangeCheck at the end should be enough.

2021-11-29 12:05 UTC, michaelholly commented on unity/Assets/Maroon/reusablePrefabs/CoordSystem/Scripts/Runtime/CoordAxis.cs
> +            foreach (var marker in GetComponentsInChildren<TextMeshPro>())
why not in _axisMarkers?

2021-11-29 12:05 UTC, michaelholly commented on unity/Assets/Maroon/reusablePrefabs/CoordSystem/Scripts/Runtime/CoordAxis.cs
> +                    throw new ArgumentOutOfRangeException();
Debug.LogWarning() or Debug.LogError() should be enough?

2021-11-29 12:05 UTC, michaelholly commented on unity/Assets/Maroon/reusablePrefabs/CoordSystem/Scripts/Runtime/CoordSystemManager.cs
> +    public class CoordSystemManager : MonoBehaviour
Can we rename this class to AxisManager/Controller or something similar

2021-11-30 19:04 UTC, dpdsw commented on unity/Assets/Maroon/reusablePrefabs/CoordSystem/SystemChangeHandler.cs
> + * Currently doing nothing
File + dependencies removed

2021-11-30 19:04 UTC, dpdsw commented on unity/Assets/Maroon/reusablePrefabs/CoordSystem/Scripts/Runtime/CoordSystem.cs
> +        public Vector3 GetPositionInWorldSpace(Vector3 localSpacePosition, Unit[] respectiveUnits)
"respectiveUnits" is now optional, calculation is adjusted accordingly ( null & Unit.None are now calculated as m)

2021-11-30 19:04 UTC, dpdsw commented on unity/Assets/Maroon/reusablePrefabs/CoordSystem/Scripts/Runtime/CoordSystemManager.cs
> +        public Vector3 GetWorldLengthsOfDirection(bool positive)
Yes, done.

2021-11-30 19:04 UTC, dpdsw commented on unity/Assets/Maroon/reusablePrefabs/CoordSystem/Scripts/Runtime/CoordSystemManager.cs
> +        private int FindInList(Axis direction)
Complicated thinking

2021-11-30 19:04 UTC, dpdsw commented on unity/Assets/Maroon/reusablePrefabs/CoordSystem/Scripts/Runtime/CoordSystemManager.cs
> +            _axisDictionary = DictionaryFromAxisList();
Complicated thinking

2021-12-01 13:34 UTC, michaelholly approved these changes

2021-12-01 13:35 UTC, merged