Feature/maroon 373 basic chess state machine
GamesResearchTUG/Maroon pull request #382
Opened 2021-12-15 08:32 UTC by jtscherko

2022-07-20 12:56 UTC, michaelholly requested changes
Please see the requested changes.

Additional Notes:

- GameObject with missing script in the scene file
- Fix error during the runtime
- Create a prefab including all experiment-relevant components
- Fix UI issues for different screen resolutions

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/reusableScripts/CommonControllers/DialogueManager.cs
> +            //SoundManager.Instance.PlaySoundEffect(typeSound);
Please revert these changes.

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/material/Black.mat
> +%YAML 1.1
Can we use also use some of the reusable materials instead?
Assets\Maroon\reusableMaterials\matSimpleColor\

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/model/chess (1).fbx.meta
> +fileFormatVersion: 2
Please rename it to "chess" (without the one in the name)

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/prefabs/small_table.fbx.meta
> +fileFormatVersion: 2
I think we need only one "table" model.
Can we delete the others?

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Direction.cs
> +
Please add a namespace to your scripts.
e.g.: Maroon.CSE.StateMachine

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Direction.cs
> +﻿using System.Collections;
Remove unused directives.

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/EnemyMove.cs
> +﻿using System.Collections;
Remove unused directives.

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/EnemyMoves.cs
> +using UnityEngine;
Remove unused directives.

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/EnemyMoves.cs
> +        if (moves == null) {
FindAll returns an empty list if there is no match!
You should check if the list is empty instead of null.

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/EnemyMoves.cs
> +        // TODO check which mode is possible for a figure
Is this ToDo still relevant?

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Field.cs
> +﻿using System.Collections;
Remove unused directives.

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Figure.cs
> +﻿using System.Collections;
Remove unused directives.

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Figure.cs
> +    public Player _player {get;set;}
Can we rename C# properties to upper case?

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Figures.cs
> +using UnityEngine;
Remove unused directives

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Figures.cs
> +        foreach(Figure figure in _figures) {
Convert into LINQ-expression
return _figures.FirstOrDefault(figure => figure._canMove && figure.gameObject.activeSelf);

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Figures.cs
> +        if (position < _figures.Count) {
Convert to ?: operator

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Figures.cs
> +        int counter = 0;
Convert into LINQ-expression
return _figures.Count(figure => figure.gameObject.activeSelf);

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/JsonResolver/JsonDirection.cs
> +﻿using System.Collections;
Remove unused directives in all JsonResolver files.

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Logger.cs
> +                GameObject stateMachineOverviewObject = GameObject.Find("StateMachineOverview");
Just create a SerializeField member and assign it in the Unity Editor instead of using GameObject.Find

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Logger.cs
> +                GameObject stateMachineOutputLog = Instantiate(GameObject.Find("StateMachineLog"));
Same here

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Logger.cs
> +                stateMachineOutputLog.transform.localScale = new Vector3(1.0f, 1.0f, 1.0f);
Use new Vector3.one

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Logger.cs
> +                textmeshObject.text = " " + logId + ": " + text;
Use string interpolation
e.g. $" {logId}: {text}"

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Map.cs
> +﻿using System.Collections;
Remove unused directives.

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Map.cs
> +    private int _amountFieldsPerRow = 8;
unused?

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Map.cs
> +    private List<List<Field>> _map = new List<List<Field>>();
you can also use a directive for List<List<Field>>
e.g. using MapList = System.Collections.Generic.List<System.Collections.Generic.List<Field>>;

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Map.cs
> +            Field field = fieldObject.GetComponent(typeof(Field)) as Field;
please use GetComponent<Field>();

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Mode.cs
> +﻿using System.Collections;
Remove unused directives.

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Mode.cs
> +    private int _modeCode;
Can we use an enum type for the mode code?

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Modes.cs
> +using UnityEngine;
remove unused directive.

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Move.cs
> +﻿using System.Collections;
remove unused directives

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Move.cs
> +    public bool isDirectionPossible(Direction directionToCheck) {
Rename it to IsDirectionPossible

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Move.cs
> +        for (int counter = 0; counter < _directions.Count; counter++) {
Convert into LINQ expression.
e.g.:  return _directions.Any(direction => direction == directionToCheck);

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Moves.cs
> +﻿using System.Collections;
Remove unused directives

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Player.cs
> +﻿using System.Collections;
Remove unused directives

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Player.cs
> +        public string _playerName {get;set;}
Rename c# properties to upper case.
e,g.: PlayerName

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Players.cs
> +using UnityEngine;
Remove unused directives

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Players.cs
> +    public Player getPlayerByName(string name) {
Please rename it to GetPlayerByName

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Ruleset.cs
> +﻿using System.Collections;
Remove unused directives

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Ruleset.cs
> +
Remove empty lines

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Ruleset.cs
> +    private int _moveDistance = 1;
unused member variable?

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Ruleset.cs
> +        List<string> data = new List<string>();
Use collection initializer
`        
List<string> data = new List<string>
        {
            _startState.GetStateName(),
            _endState.GetStateName(),
            _direction.GetDirectionName(),
            _mode.GetModeName()
        };`

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Rulesets.cs
> +using UnityEngine;
Remove unused directives

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Rulesets.cs
> +                }
Fix indentation problem

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Rulesets.cs
> +                }
Fix indentation problem

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Rulesets.cs
> +                    return (false, "ErrorSameRuleTwice");
maybe we should handle this with exceptions instead of a false/string pair

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Rulesets.cs
> +    public Ruleset GetRulesetAtPosition(int position) {
Fix typo in method name.

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Scenario.cs
> +using System.IO;
Remove unused directives

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Scenario.cs
> +            if (jsonScenario.playerToPlay == player._playerName) {
Convert it to ?: expression

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Scenario.cs
> +        // initialse moveable figures
there is a typo in this comment

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Scenario.cs
> +            Debug.LogFormat("There is destination definded ({0}.json)", _scenarioName);
there is a typo in this line

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Scenario.cs
> +        if (jsonScenario.mustHitAllEnemies) {
Convert it to ?: expression

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Scenario.cs
> +                Debug.LogFormat("There is no column defined (figures: line {0}, {1}.json)", figureLineNumber, _scenarioName);
Use Debug.Log with string interpolation
Debug.Log($"There is no column defined (figures: line {figureLineNumber}, {_scenarioName}.json)");

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/State.cs
> +﻿using System.Collections;
Remove unused directives

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/State.cs
> +        //_stateName = name;
???

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/States.cs
> +    void Start() {
use explicit "private" modifier

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/States.cs
> +    private void initDropdownMenus() {
Rename to InitDropdownMenus

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/States.cs
> +    public void initDropdownMenu(string dropdownName, string state) {
Rename to InitDropdownMenu

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/States.cs
> +    public void addOption(string option) {
Rename to AddOption

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/States.cs
> +    public void addDropdownOption(string dropdownName, string optionName) {
Rename to AddDropdownOption

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/States.cs
> +    public void addState() {
Rename AddState

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Surrounding.cs
> +﻿using System.Collections;
Remove unused directives

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Surrounding.cs
> +    void Start() {
Use explicit "private" modifier

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Surrounding.cs
> +        _surroundingFieldObjects.Add(GameObject.Find("UpperLeftButton"));
Mark the _surroundingFieldObjects list as SerializedField and assign the objects in the Unity Inspector.

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/SurroundingField.cs
> +﻿using System.Collections;
Remove unused directives

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/SurroundingField.cs
> +    private List<string> _names = new List<string>();
change the initalization to:
private List<string> _names = new List<string>() {" ", "E", "W", "B"};

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/GameController.cs
> +        private Player _playerToPlay;
unused?

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/GameController.cs
> +        void Start()
use explicit "private" modifier

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/GameController.cs
> +            _states = test.GetComponent(typeof(States)) as States;
Use `GetComponent<States>()`

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/GameController.cs
> +            Dropdown dropdown = dropdownObject.GetComponent(typeof(Dropdown)) as Dropdown;
Use `GetComponent<Dropdown>()`

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/GameController.cs
> +            Dropdown dropdown = dropdownObject.GetComponent(typeof(Dropdown)) as Dropdown;
Use `GetComponent<Dropdown>()`

2022-07-20 12:56 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/GameController.cs
> +          /*   rulesetTextBackgroundObject.transform.SetParent(rulesetTextTableObject.transform);
Remove unused code

2022-07-20 17:52 UTC, jtscherko commented on unity/Assets/Maroon/reusableScripts/CommonControllers/DialogueManager.cs
> +            //SoundManager.Instance.PlaySoundEffect(typeSound);
Done

2022-07-20 18:07 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/material/Black.mat
> +%YAML 1.1
i changed the color but there is no cool white

2022-07-20 18:09 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/model/chess (1).fbx.meta
> +fileFormatVersion: 2
done

2022-07-20 18:10 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/prefabs/small_table.fbx.meta
> +fileFormatVersion: 2
done

2022-07-20 18:24 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Direction.cs
> +
hope this is correct

2022-07-20 18:25 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Direction.cs
> +﻿using System.Collections;
done

2022-07-20 18:25 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/EnemyMove.cs
> +﻿using System.Collections;
Done

2022-07-20 18:27 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/EnemyMoves.cs
> +using UnityEngine;
done

2022-07-20 18:28 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/EnemyMoves.cs
> +        if (moves == null) {
Done

2022-07-20 18:28 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/EnemyMoves.cs
> +        // TODO check which mode is possible for a figure
Just would be relevant when other figures should be moved

2022-07-20 18:29 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Field.cs
> +﻿using System.Collections;
done

2022-07-20 18:30 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Figure.cs
> +﻿using System.Collections;
done

2022-07-20 18:32 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Figure.cs
> +    public Player _player {get;set;}
Do you mean without underscore? or do you mean the get/set?

2022-07-20 18:33 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Figures.cs
> +using UnityEngine;
done

2022-07-20 18:39 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Figures.cs
> +        foreach(Figure figure in _figures) {
done

2022-07-20 18:40 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Figures.cs
> +        if (position < _figures.Count) {
done

2022-07-20 18:45 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Figures.cs
> +        int counter = 0;
done

2022-07-20 18:52 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/JsonResolver/JsonDirection.cs
> +﻿using System.Collections;
done

2022-07-20 19:11 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Logger.cs
> +                GameObject stateMachineOverviewObject = GameObject.Find("StateMachineOverview");
According to several posts in the forum, this is not possible

2022-07-20 19:11 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Logger.cs
> +                GameObject stateMachineOutputLog = Instantiate(GameObject.Find("StateMachineLog"));
According to several posts in the forum, this is not possible

2022-07-20 19:13 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Logger.cs
> +                stateMachineOutputLog.transform.localScale = new Vector3(1.0f, 1.0f, 1.0f);
Resolved

2022-07-20 19:15 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Logger.cs
> +                textmeshObject.text = " " + logId + ": " + text;
resolved

2022-07-20 19:15 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Map.cs
> +﻿using System.Collections;
resolved

2022-07-20 19:16 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Map.cs
> +    private int _amountFieldsPerRow = 8;
removed

2022-07-20 19:22 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Map.cs
> +    private List<List<Field>> _map = new List<List<Field>>();
Resolved

2022-07-20 19:27 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Map.cs
> +            Field field = fieldObject.GetComponent(typeof(Field)) as Field;
how should this work?

2022-07-20 19:27 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Mode.cs
> +﻿using System.Collections;
resolved

2022-07-20 19:37 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Mode.cs
> +    private int _modeCode;
resolved

2022-07-20 19:38 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Modes.cs
> +using UnityEngine;
they are all needed

2022-07-20 19:38 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Move.cs
> +﻿using System.Collections;
resolved

2022-07-20 19:39 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Move.cs
> +    public bool isDirectionPossible(Direction directionToCheck) {
resolved

2022-07-20 19:41 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Move.cs
> +        for (int counter = 0; counter < _directions.Count; counter++) {
resolved

2022-07-20 19:42 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Moves.cs
> +﻿using System.Collections;
resolved

2022-07-20 19:44 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Player.cs
> +﻿using System.Collections;
resolved

2022-07-20 19:45 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Players.cs
> +using UnityEngine;
resolved

2022-07-20 19:48 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Players.cs
> +    public Player getPlayerByName(string name) {
resolved

2022-07-20 19:49 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Ruleset.cs
> +﻿using System.Collections;
resolved

2022-07-20 19:50 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Ruleset.cs
> +
resolved

2022-07-20 19:51 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Ruleset.cs
> +    private int _moveDistance = 1;
removed

2022-07-20 19:53 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Ruleset.cs
> +        List<string> data = new List<string>();
resolved

2022-07-20 19:53 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Rulesets.cs
> +using UnityEngine;
resolved

2022-07-20 20:13 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Rulesets.cs
> +                }
resolved (in a nice way)

2022-07-20 20:13 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Rulesets.cs
> +                }
resolved (in a nice way)

2022-07-20 20:17 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Rulesets.cs
> +    public Ruleset GetRulesetAtPosition(int position) {
what do you mean?

2022-07-20 20:20 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Scenario.cs
> +using System.IO;
resolved

2022-07-20 20:21 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Scenario.cs
> +            if (jsonScenario.playerToPlay == player._playerName) {
resolved

2022-07-20 20:21 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Scenario.cs
> +        // initialse moveable figures
resolved

2022-07-20 20:23 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Scenario.cs
> +            Debug.LogFormat("There is destination definded ({0}.json)", _scenarioName);
resolved

2022-07-20 20:24 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Scenario.cs
> +        if (jsonScenario.mustHitAllEnemies) {
resolved

2022-07-20 20:32 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Scenario.cs
> +                Debug.LogFormat("There is no column defined (figures: line {0}, {1}.json)", figureLineNumber, _scenarioName);
Resolved for all instances

2022-07-20 20:34 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/State.cs
> +﻿using System.Collections;
resolved

2022-07-20 20:34 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/State.cs
> +        //_stateName = name;
don´t know why

2022-07-20 20:35 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Rulesets.cs
> +                    return (false, "ErrorSameRuleTwice");
maybe

2022-07-20 20:39 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/States.cs
> +    void Start() {
resolved

2022-07-20 20:40 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/GameController.cs
> +        void Start()
resolved

2022-07-20 20:40 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Surrounding.cs
> +    void Start() {
resolved

2022-07-20 20:41 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/States.cs
> +    private void initDropdownMenus() {
resolved

2022-07-20 20:42 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/States.cs
> +    public void initDropdownMenu(string dropdownName, string state) {
resolved

2022-07-20 20:42 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/States.cs
> +    public void addOption(string option) {
resolved

2022-07-20 20:42 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/States.cs
> +    public void addDropdownOption(string dropdownName, string optionName) {
resolved

2022-07-20 20:43 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/States.cs
> +    public void addState() {
Resolved

2022-07-20 20:43 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Surrounding.cs
> +﻿using System.Collections;
resolved

2022-07-20 20:49 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Surrounding.cs
> +        _surroundingFieldObjects.Add(GameObject.Find("UpperLeftButton"));
resolved

2022-07-20 20:50 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/SurroundingField.cs
> +﻿using System.Collections;
resolved

2022-07-20 20:50 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/SurroundingField.cs
> +    private List<string> _names = new List<string>();
resolved

2022-07-20 20:51 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/GameController.cs
> +        private Player _playerToPlay;
is removed

2022-07-20 20:52 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/GameController.cs
> +            _states = test.GetComponent(typeof(States)) as States;
resolved

2022-07-20 20:54 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/GameController.cs
> +            Dropdown dropdown = dropdownObject.GetComponent(typeof(Dropdown)) as Dropdown;
resolved

2022-07-20 20:54 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/GameController.cs
> +            Dropdown dropdown = dropdownObject.GetComponent(typeof(Dropdown)) as Dropdown;
resolved

2022-07-20 20:58 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/GameController.cs
> +          /*   rulesetTextBackgroundObject.transform.SetParent(rulesetTextTableObject.transform);
resolved

2022-07-20 21:16 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Figure.cs
> +    public Player _player {get;set;}
yes we can

2022-07-20 21:21 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Player.cs
> +        public string _playerName {get;set;}
in the other projects there also is no upper case

2022-07-20 21:23 UTC, jtscherko commented on unity/Assets/Maroon/scenes/experiments/StateMachine/scripts/Figure.cs
> +    public Player _player {get;set;}
in the other experiments there is also this format (_name)

2022-07-21 15:47 UTC, michaelholly approved these changes

2022-07-21 15:48 UTC, merged