WIP Feature/maroon 394 coord voltmeter
GamesResearchTUG/Maroon pull request #397
Opened 2022-03-11 08:57 UTC by dpdsw

2022-03-25 09:28 UTC, michaelholly requested changes

2022-03-25 09:28 UTC, michaelholly commented on unity/Assets/Maroon/reusableGui/Experiment/Resources/Tools/VoltmeterUI.prefab
> +%YAML 1.1
Maybe rename VoltmeterUI and RulerUI to Voltmeter and Ruler

2022-03-25 09:28 UTC, michaelholly commented on unity/Assets/Maroon/reusablePrefabs/NewVoltmeter/Example/VoltmeterExample.unity
> +%YAML 1.1
ArgumentOutOfRangeException in the play mode

2022-03-25 09:28 UTC, michaelholly commented on unity/Assets/Maroon/reusablePrefabs/NewVoltmeter/Scripts/VoltmeterCharge.cs
> +    public class VoltmeterCharge : MonoBehaviour, IGenerateE
why another charge?

Charge in Assets\Maroon\reusableScripts\Physics\Electromagnetism
Charge in Assets\Maroon\scenes\experiments\Capacitor\Scripts
CoulombChargeBehaviour in Assets\Maroon\scenes\experiments\CoulombsLaw\Scripts

Please reuse the Charge in Assets\Maroon\reusableScripts\Physics\Electromagnetism for your purpose

2022-03-25 09:28 UTC, michaelholly commented on unity/Assets/Maroon/reusablePrefabs/NewVoltmeter/Scripts/VoltmeterPinPoint.cs
> +    public class VoltmeterPinPoint : MonoBehaviour, IResetObject
why does this class not inherit from the Pin class?

2022-04-10 14:29 UTC, dpdsw commented on unity/Assets/Maroon/reusableGui/Experiment/Resources/Tools/VoltmeterUI.prefab
> +%YAML 1.1
Done

2022-04-10 14:30 UTC, dpdsw commented on unity/Assets/Maroon/reusablePrefabs/NewVoltmeter/Example/VoltmeterExample.unity
> +%YAML 1.1
SceneManager expects '.' in the scene name. Renamed Example scenes

2022-04-10 14:40 UTC, dpdsw commented on unity/Assets/Maroon/reusablePrefabs/NewVoltmeter/Scripts/VoltmeterPinPoint.cs
> +    public class VoltmeterPinPoint : MonoBehaviour, IResetObject
It does now

2022-04-10 14:59 UTC, dpdsw commented on unity/Assets/Maroon/reusablePrefabs/NewVoltmeter/Scripts/VoltmeterCharge.cs
> +    public class VoltmeterCharge : MonoBehaviour, IGenerateE
Done

2022-04-13 08:46 UTC, michaelholly commented
Bug in Voltmeter UI: if the user drags the voltmeter pins from the UI into the scene, the position in the UI view is not updated.
The fix would be to call the UpdateDisplay methods in the OnEnabled event in the PC_Drag Handler for VoltmeterPos and VoltmeterNeg
 
![image](https://user-images.githubusercontent.com/11720008/163137526-cb4bbad3-89ee-46aa-861d-ce2dd8f83a7a.png)

2022-04-29 08:30 UTC, michaelholly approved these changes

2022-04-29 08:33 UTC, merged