Feature/maroon 200 vr plugin
GamesResearchTUG/Maroon pull request #403
Opened 2022-05-09 14:14 UTC by sandra-bre

2022-06-13 13:51 UTC, michaelholly commented
@.gitignore
Can we please use the file pattern instead of adding all lightning folders?

e.g.: 
# Lightning

LightingData.asset*
Lightmap-0_comp_dir.png*
Lightmap-0_comp_dir.exr*
Lightmap-0_comp_shadowmask*
Lightmap-0_comp_light.exr*
Lightmap-1_comp_dir.png*
Lightmap-1_comp_dir.exr*
Lightmap-1_comp_shadowmask*
Lightmap-1_comp_light.exr*
Lightmap-2_comp_dir.png*
Lightmap-2_comp_dir.exr*
Lightmap-2_comp_shadowmask*
Lightmap-2_comp_light.exr*
ReflectionProbe-0.exr*

2022-07-11 12:07 UTC, michaelholly requested changes

2022-07-11 12:07 UTC, michaelholly commented on unity/Assets/Brick Project Studio.meta
> +fileFormatVersion: 2
Please move it to the Vendor folder and check if we need everything in this folder.

2022-07-11 12:07 UTC, michaelholly commented on unity/Assets/Editor/WaterPlaneEditor.cs
> -public class WaterPlaneEditor : Editor
Why did you delete this file?

2022-07-11 12:07 UTC, michaelholly commented on unity/Assets/Maroon/GlobalEntities/Network/prefabs/NetworkStation.prefab
>    m_Children:
Do we need these changes?

2022-07-11 12:07 UTC, michaelholly commented on unity/Assets/Maroon/GlobalEntities/Network/prefabs/NetworkManager.prefab
>    m_Name:
Do we need these changes?

2022-07-11 12:07 UTC, michaelholly commented on unity/Assets/Maroon/GlobalEntities/SceneManager/Materials/FaradaysLawMaterial.mat
> +%YAML 1.1
Can we move these files (materials and images) to the experiment-related folders?

2022-07-11 12:07 UTC, michaelholly commented on unity/Assets/Maroon/MaybeGlobalEntities/questManager/Scripts/QuestChecks/HuygensPrinciple/ChangeDecoCheck.cs
> +using System;
I think we should move this to another folder, because it should be available in all experiments.

2022-07-11 12:07 UTC, michaelholly commented on unity/Assets/Maroon/MaybeGlobalEntities/questManager/Scripts/QuestChecks/HuygensPrinciple/ChangeDecoCheck.cs
> +            var decoCollection = FindObjectOfType<DecoObjectCollection>();
Do we really need the "DecoObjectCollection" type?
We can use a Tag instead of that to search for deco objects.
GameObject.FindGameObjectsWithTag

2022-07-11 12:07 UTC, michaelholly commented on unity/Assets/Maroon/MaybeGlobalEntities/simulationController/scripts/SimulationController.cs
> +    public UnityEvent onEnteredScene;
Do we need this?
When yes, I think it is not the right place for it.

2022-07-11 12:07 UTC, michaelholly commented on unity/Assets/Maroon/reusableFonts/Poppins/FontVariants/Poppins-BoldItalic.asset
>    m_Script: {fileID: 11500000, guid: 71c1514a6bd24e1e882cebbe1904ce04, type: 3}
Why did you change all of these font assets?

2022-07-11 12:07 UTC, michaelholly commented on unity/Assets/Maroon/reusableGui/Menu/PrefabsBase/preMenuButton.prefab
> -  m_Script: {fileID: 1679637790, guid: f70555f144d8491a825f0804e09c671c, type: 3}
Why changed?

2022-07-11 12:07 UTC, michaelholly commented on unity/Assets/Maroon/reusableGui/Menu/PrefabsColumns/scrMenuColumnLaboratorySelection.cs
> +using Valve.VR.InteractionSystem;
Remove unused directives

2022-07-11 12:07 UTC, michaelholly commented on unity/Assets/Maroon/reusableGui/Menu/PrefabsColumns/scrMenuColumnLanguage.cs
> +using Valve.VR.InteractionSystem;
Remove unused directives.

2022-07-11 12:07 UTC, michaelholly commented on unity/Assets/Maroon/reusablePrefabs/Drawer/Scripts/VRScrollingHelper.cs
> +        if (_firstUpdate) //need this otherwise not all StartFunctions of our controls are being called
Maybe this can be fixed by changing the script execution order.

2022-07-11 12:07 UTC, michaelholly commented on unity/Assets/Maroon/reusableScripts/PausableObject.cs
> +		protected virtual void Awake()
Empty Awake() function?

2022-07-11 12:07 UTC, michaelholly commented on unity/Assets/Maroon/reusableScripts/Physics/Electromagnetism/FieldLine.cs
> +            var tmp = GetFieldStrengthFromEmObj();
unused?

2022-07-11 12:07 UTC, michaelholly commented on unity/Assets/Maroon/reusableScripts/Tools/VRShelve/HeightAdapter.cs
> +using System.Collections;
Can we move this to \Assets\Maroon\reusablePrefabs\Drawer\Scripts ?

2022-07-11 12:07 UTC, michaelholly commented on unity/Assets/Maroon/reusableScripts/Tools/VRShelve/HelperCondition.cs
> +public class HelperCondition : MonoBehaviour
Can we move this to \Assets\Maroon\reusablePrefabs\Drawer\Scripts?
What is this script for? Maybe change the name and add comments.

2022-07-11 12:07 UTC, michaelholly commented on unity/Assets/Maroon/reusableScripts/Tools/VRShelve/LanguageChangeHelper.cs
> +public class LanguageChangeHelper : MonoBehaviour
Can we move this to \Assets\Maroon\reusablePrefabs\Drawer\Scripts ?

2022-07-11 12:07 UTC, michaelholly commented on unity/Assets/Maroon/reusableScripts/Tools/VRShelve/LanguageChangeHelper.cs
> +    [SerializeField] private UnityEvent onSwitchToGerman;
Do we need these events?
We can use the LanguageManager.OnLanguageChanged(System.Language) event.

2022-07-11 12:07 UTC, michaelholly commented on unity/Assets/Maroon/reusableScripts/Tools/VRShelve/WheelAdjuster.cs
> +public class WheelAdjuster : MonoBehaviour
Can we move it to \Assets\Maroon\reusablePrefabs\Drawer\Scripts?

2022-07-11 12:23 UTC, sandra-bre commented on unity/Assets/Maroon/MaybeGlobalEntities/questManager/Scripts/QuestChecks/HuygensPrinciple/ChangeDecoCheck.cs
> +using System;
Own folder ..QuestChecks/Customization

2022-07-11 12:30 UTC, sandra-bre commented on unity/Assets/Maroon/MaybeGlobalEntities/simulationController/scripts/SimulationController.cs
> +    public UnityEvent onEnteredScene;
onEnteredScence -> rename to onSimulationLoaded

2022-07-11 12:34 UTC, sandra-bre commented on unity/Assets/Maroon/reusablePrefabs/Drawer/Scripts/VRScrollingHelper.cs
> +        if (_firstUpdate) //need this otherwise not all StartFunctions of our controls are being called
Edit - Project Settings - Script Execution Order: try adding the script after Default Time and check if the bool is still needed

2022-07-11 12:49 UTC, sandra-bre commented on unity/Assets/Brick Project Studio.meta
> +fileFormatVersion: 2
deleted

2022-07-11 12:50 UTC, sandra-bre commented on unity/Assets/Maroon/GlobalEntities/Network/prefabs/NetworkStation.prefab
>    m_Children:
added teleport point for VR

2022-07-11 12:52 UTC, sandra-bre commented on unity/Assets/Maroon/GlobalEntities/Network/prefabs/NetworkManager.prefab
>    m_Name:
added teleport point

2022-07-11 13:33 UTC, sandra-bre commented on unity/Assets/Maroon/GlobalEntities/SceneManager/Materials/FaradaysLawMaterial.mat
> +%YAML 1.1
done

2022-07-11 14:58 UTC, sandra-bre commented on unity/Assets/Maroon/reusableScripts/Tools/VRShelve/LanguageChangeHelper.cs
> +    [SerializeField] private UnityEvent onSwitchToGerman;
yes, because of the VR Buttons (as discussed)

2022-07-11 15:00 UTC, sandra-bre commented on unity/Assets/Maroon/reusableScripts/Physics/Electromagnetism/FieldLine.cs
> +            var tmp = GetFieldStrengthFromEmObj();
removed

2022-07-11 16:14 UTC, sandra-bre commented on unity/Assets/Maroon/reusableScripts/PausableObject.cs
> +		protected virtual void Awake()
removed

2022-07-11 16:33 UTC, sandra-bre commented on unity/Assets/Editor/WaterPlaneEditor.cs
> -public class WaterPlaneEditor : Editor
here again

2022-07-11 16:39 UTC, sandra-bre commented on unity/Assets/Maroon/MaybeGlobalEntities/questManager/Scripts/QuestChecks/HuygensPrinciple/ChangeDecoCheck.cs
> +            var decoCollection = FindObjectOfType<DecoObjectCollection>();
cannot remove this, as not all gameobjects are active -> FindGameObjectsWithTag can only find active gameobjects, hence I created a script/list for that

2022-07-21 08:44 UTC, GameLabGrazTrainee commented
VandeGraaffGenerator.pc : 
missing material for field lines 
when clicking on the stop button the generator is not discharging

2022-07-25 07:49 UTC, michaelholly commented
![image](https://user-images.githubusercontent.com/11720008/180725640-73d188d7-20b8-4bd2-9cda-e2cf4b456f32.png)

2022-07-29 09:29 UTC, michaelholly commented
![image](https://user-images.githubusercontent.com/11720008/181729728-9f4f4ae4-110b-4dd4-8b39-161fdd1f0e63.png)

2022-07-29 09:35 UTC, michaelholly commented
Please fix the missing material
![image](https://user-images.githubusercontent.com/11720008/181730822-19e9f77b-fee3-47df-9d32-acc637d476e7.png)

2022-07-29 14:03 UTC, michaelholly commented
![image](https://user-images.githubusercontent.com/11720008/181777071-d462d585-93e7-433f-98e4-0dcc980e6e12.png)

2022-07-29 14:04 UTC, michaelholly commented
Can we delete the CoulombsLaw.vr scene?

2022-07-29 14:10 UTC, michaelholly commented
![image](https://user-images.githubusercontent.com/11720008/181778372-88f0797d-ed31-4974-b64c-8e61e48f48cd.png)

2022-08-01 09:35 UTC, sandra-bre commented
> Can we delete the CoulombsLaw.vr scene?

2022-08-02 13:05 UTC, michaelholly commented
The 2D Debug function is not working.

"NullReferenceException: Object reference not set to an instance of an object
Valve.VR.InteractionSystem.SnapTurn.Update () (at Library/PackageCache/com.gamelabgraz.vrinteraction@b66d897d69/3rd Party/SteamVR/InteractionSystem/SnapTurn/SnapTurn.cs:67)"

![image](https://user-images.githubusercontent.com/11720008/182381663-a68c0fc0-41cc-474c-89dc-d4faa70a768b.png)

2022-08-02 13:16 UTC, michaelholly commented
Can we replace the table model in the experiment prefab and in the laboratory block prefab so that it is consistent for PC and VR.

2022-08-02 13:38 UTC, michaelholly commented
What about this VRPlayer in "Assets\Maroon\SharedEntities\Player\ModeVirtualReality"?
Can we delete this prefab?

2022-08-04 07:51 UTC, michaelholly commented
Please enable the roof and walls object in the experiment template vr scene.
There is also an empty "Table" object in the scene.
As defined in the wiki, the door object has to be at position 0,0,0. Please change this for the experimentsetting.vr prefab and apply the changes to all vr experiment scenes.

![image](https://user-images.githubusercontent.com/11720008/182793077-57cac238-5331-4d08-b8e2-e0c08966425c.png)

2022-08-04 07:55 UTC, michaelholly commented
in the experiment template vr scene are two whiteboards included
![image](https://user-images.githubusercontent.com/11720008/182794510-a7d8af5c-1cc8-423c-b45e-1db969b8845b.png)

2022-08-04 08:10 UTC, michaelholly commented
MainMenu.vr screen model is missing
![image](https://user-images.githubusercontent.com/11720008/182797358-4cef497b-5a1f-43d7-a313-745c6b2d52c1.png)

2022-08-04 08:46 UTC, michaelholly commented
Can we add/enable the exit door to the mainmenu vr scene to exit the application?
Can we also change the position of the drawer object so that is more usable?
Can we lock the experiment drawer for this scene?

2022-08-04 09:07 UTC, michaelholly commented
When loading a VR scene from the main menu vr scene, teleporting does not work.

2022-08-04 10:10 UTC, michaelholly commented
> When loading a VR scene from the main menu vr scene, teleporting does not work.

2022-08-04 10:14 UTC, sandra-bre commented
> The 2D Debug function is not working.
> 
> "NullReferenceException: Object reference not set to an instance of an object Valve.VR.InteractionSystem.SnapTurn.Update () (at Library/PackageCache/com.gamelabgraz.vrinteraction@b66d897d69/3rd Party/SteamVR/InteractionSystem/SnapTurn/SnapTurn.cs:67)"
> 
> ![image](https://user-images.githubusercontent.com/11720008/182381663-a68c0fc0-41cc-474c-89dc-d4faa70a768b.png)

same in the utilities project - will be done after the PR

2022-08-04 10:37 UTC, sandra-bre commented
> Please enable the roof and walls object in the experiment template vr scene. There is also an empty "Table" object in the scene. As defined in the wiki, the door object has to be at position 0,0,0. Please change this for the experimentsetting.vr prefab and apply the changes to all vr experiment scenes.
> 
> ![image](https://user-images.githubusercontent.com/11720008/182793077-57cac238-5331-4d08-b8e2-e0c08966425c.png)

setting the door position will be done in an own issue

2022-08-18 15:02 UTC, michaelholly requested changes

2022-08-18 15:02 UTC, michaelholly commented on unity/Assets/Maroon/reusablePrefabs/experimentSetting/_ExperimentSetting.vr.prefab
> +%YAML 1.1
Why there are two ExperimentSetting.vr prefabs???

2022-08-18 15:02 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/HuygensPrinciple/materials/Wall_Green.mat
> +%YAML 1.1
I think we should move those materials somewhere else since they are also used in other experiments.

2022-08-18 15:02 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/HuygensPrinciple/materials/triplaner.shader
> +Shader "Tri-Planar World" {
Move this to another folder.

2022-08-18 15:02 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/HuygensPrinciple/scripts/CustomizationGameObjectChanger.cs
> +using System.Collections;
Move all of the customization-related assets to one experiment independent folder.

2022-08-18 15:02 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/HuygensPrinciple/scripts/ResetLinearDrive.cs
> +using System;
I think this is also located in a wrong folder

2022-08-18 19:50 UTC, sandra-bre commented on unity/Assets/Maroon/scenes/experiments/HuygensPrinciple/materials/Wall_Green.mat
> +%YAML 1.1
customization folder?

2022-08-22 08:37 UTC, sandra-bre commented on unity/Assets/Maroon/reusablePrefabs/experimentSetting/_ExperimentSetting.vr.prefab
> +%YAML 1.1
removed unused one

2022-08-22 08:44 UTC, sandra-bre commented on unity/Assets/Maroon/scenes/experiments/HuygensPrinciple/materials/Wall_Green.mat
> +%YAML 1.1
done

2022-08-22 08:45 UTC, sandra-bre commented on unity/Assets/Maroon/scenes/experiments/HuygensPrinciple/materials/triplaner.shader
> +Shader "Tri-Planar World" {
reusableShader

2022-08-22 17:14 UTC, michaelholly commented
Missing Prefab in the cCapacitor.vr scene
![image](https://user-images.githubusercontent.com/11720008/185980276-dc37c412-70cf-418f-8e13-eade132df062.png)

2022-08-22 19:05 UTC, michaelholly commented
Final test required.

2022-08-23 16:06 UTC, michaelholly approved these changes

2022-08-23 16:10 UTC, merged