Feature/maroon 424 planetary system
GamesResearchTUG/Maroon pull request #442
Opened 2023-06-01 21:51 UTC by Lowfi001

Closes #424

2023-06-20 12:16 UTC, michaelholly requested changes

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/FBX/big_box.fbx
Please rename it to e.g. planet_box or something similar.

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/FBX/big_box.fbx
This object has many vertices. Please try to reduce the number of vertices for this model.

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/FBX/saturn_ring_generated.fbx
same, many vertices for a simple object

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/FBX/telescope_parts/telescope_1_base.fbx
i think we can remove the detailed version (telescope_pars)

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/FBX/telescope_reduced/telescope_reduced.fbx
Please use a name without "reduced" after deleting the detailed version.

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Materials/SunParticles.mat
Please follow the same naming convention for all material files.

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Materials/particleSystems/0.mat
Please use a meaningful name for all particle materials. e.g. particle_0.mat

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Materials/screensAnndPictures/PlanetChart.mat
Please fix the typo in the folder name "screensAnndPicture".

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Materials/trajectories/0.mat
Please use a meaningful name for all trajectory materials e.g. trajectory_0.

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/PlanetarySystem.pc.unity
Please create a prefab for your experiment including the "Animation" and "Sorting Minigame" objects to reuse it for the VR scene.

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Prefabs/Environment/Interactable.prefab
Please follow the same naming convention for all prefabs.

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Prefabs/Environment/PC peripherals.prefab
The fbx model is located in the reusablePrefabs folder. Please move the prefab to the corresponding folder.

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Prefabs/Environment/PcTable.prefab
same

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Prefabs/Environment/Whiteboard 1.prefab
Please rename it to e.g. WhiteboardVariant

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Prefabs/Environment/pictures blurred 1.prefab
Rename it without the number at the end.

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Prefabs/Environment/plants.prefab
This prefab is useless. It just contains the different plant prefabs at different positions which can simply be used in the scene.

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Prefabs/Environment/telescope_reduced.prefab
Rename it to "telescope" without "reduced".

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Prefabs/planets solarsystem/0_sun Variant.prefab
changes in the scene are not applied on the planet prefabs.
e.g. Planet Information Of and Planet Info property

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Prefabs/planets solarsystem/3_earth.prefab
names are not consistent.

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Prefabs/planets sorting game/1 sorting planet Variant.prefab
scene changes are not applied on the sorting planet prefabs.
e.g. Planet Info

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Resources/MLG/planetarySystem.xml
> +		<Translation Key="Newton">
Please fix the indention issues. e.g. Tab vs Spaces

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Resources/MLG/laboratory.xml
> +		<Translation Key="EnterPlanetarySystemExperiment">
Fix the indention issues.

2023-06-20 12:16 UTC, michaelholly commented on unity/ProjectSettings/ProjectSettings.asset
Please double-check if we need all the ProjectSettings changes.

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/FlyCamera.cs
please add a namespace for all of your scripts
e.g. Maroon.Experiments.PlanetarySystem

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/FlyCamera.cs
> +    void Start()
Use explicit private modifier.

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/FlyCamera.cs
> +            Debug.Log("FlyCamera: Start(): Sun not assigned.");
We should keep the debug message neutral.
e.g. "FlyCamera: Start: camera focus not assigned."

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/FlyCamera.cs
> +    void Update()
use private

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/FlyCamera.cs
> +    void FlyCamerMovement()
use private
fix the typo in the function name.

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/FlyCamera.cs
> +    private void LookAtFokus()
Fix the typo in the function name.

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/HideUI.cs
> +            AnimationUI.SetActive(false);
I think we can simplify this section to:
AnimationUI.SetActive(!hide);
PlanetInformationUI.SetActive(!hide);

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/PlanetInfo.cs
> +    sun_0,
Please rename it to upper case and remove the value from the name.

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/PlanetInfo.cs
> +    empty
"Unknown" would be a better wording for it?

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/PlanetInfo.cs
> +    public static PlanetInfo Instance
Why do we need a static instance property for this class?
FindObjectOfType returns the first object in the scene and there are multiple planets with this class...

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/PlanetInfo.cs
> +                mass                            = 1988500f;
Why not via the inspector?

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/PlanetRotation.cs
> +    void FixedUpdate()
add private

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/PlanetRotation.cs
> +        //transform.Rotate(new Vector3(0, ((360 / -planetInfo.rotationPeriod) * (ROTATION_PERIOD_SCALE_FACTOR)), 0) * Time.deltaTime);
please remove unused code

2023-06-20 12:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/PlanetaryController.cs
> +    [SerializeField] private Toggle toggleAllTrajectories;
We need to remove all of these UI dependencies from the planetary controller

2024-09-18 12:14 UTC, FlorianGlawogger requested changes
Hi, I merged your branch with develop.
I really like the experiment, the planets look very cool and the simulation/sorting game is quite fun to play with!
I looked at the code, and I think the main thing that's still some work is splitting up the PlanetaryController into multiple files. 
But again: cool experiment 👍

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Tests/EditModeTests/ContentValidation/PcSceneValidationTests.cs
> +        [SkipTestForScenesWithReason("PlanetarySystem", ReasonIntentionallyMissing)]
Do you need the other EventSystem? I think if you delete your new eventsystem and use the one from the prefab, then the test should be ok and you don't have to skip it?

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Tests/EditModeTests/ContentValidation/PcSceneValidationTests.cs
> +        [SkipTestForScenesWithReason("Optics, PlanetarySystem", ReasonIntentionallyMissing)]
Do you need your own UI Controls Panel? Because I think it should also be possible to use the prefab one, you could use start/pause for pausing the planet simulation/unpausing it. You could use the reset button from them, the arrow back to the laboratory/main menu is also there. The only thing that's missing is your "house" icon, but maybe you can also add that to the prefab. (IMO the house icon is a bit confusing though, because I assumed it would take me back to the main menu and the arrow takes me back to the start of your experiment, but actually it's the other way around. I know the arrow is not from your experiment. Maybe we should somewhere down the line replace the arrow with your house. For now I think it'd be best to use a different symbol than the house for your purpose of returning to the start of the planet simulation experiment. Another option would be to use a regular UI button in the top left corner or something.

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Tests/EditModeTests/ContentValidation/PcSceneValidationTests.cs
> +        [SkipTestForScenesWithReason("PlanetarySystem", ReasonIntentionallyMissing)]
As fas as I can tell, there is no reason you use a new UI Panel Dialogue instead of the one already existing/from the prefab?

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Tests/EditModeTests/ContentValidation/PcSceneValidationTests.cs
> +        [SkipTestForScenesWithReason("PlanetarySystem", ReasonIntentionallyMissing)]
see comment above regarding UI Panel, please use the things that are already provided, If you need a white arrow because it works better with your dark space-themed elements, you can also change the image the button prefab uses in your experiment.

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Tests/EditModeTests/ContentValidation/PcSceneValidationTests.cs
> +        [SkipTestForScenesWithReason("PlanetarySystem", ReasonIntentionallyMissing)]
You could just enable the panel by default, and disable it when the scene starts. (In fact I think you actually already do that)

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Textures/SolarTextures/black_skybox.gif
Is there a reason why this is a .gif file?

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/StartSortingGame.cs
StartSortingGame and StartAnimation are basically the same class, they just call a different method OnMouseDown, you could also just have 1 class instead, and have a UnityEvent that gets invoked when OnMouseDown, and then in the inspector you connect your planetaryController.StartAnimationOnInput/StartSortingGame or whatever.

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/StartAnimation.cs
see comment(s) in StartSortingGame.cs

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/StartSortingGame.cs
> +    }
It would be cool also to use OnMouseEnter and OnMouseExit to have a hover effect (change screen background color when mouse hovers)
A good solution would also be to simply use a Button script

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/SortingPlanetsDragAndDrop.cs
> +        private void CreatePlanetInfoMessage()
IMO this method should be moved to `PlanetInfo` class

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/SortingPlanetsDragAndDrop.cs
> +            messageTMP = GetMessagByKey("PlanetInfo0");
Moon and Sun are also not planets? Maybe either "celestial body"/"Himmelskörper", or keep "Planet" for the planets and for Moon and Sun (and pluto?) have some other naming

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/SortingPlanetsDragAndDrop.cs
> +            planetInfoMessage += " " + messageTMP + " " + GetMessagByKey(planetInfo.PlanetInformationOf.ToString()) + "\n\n";
Currently in the sorting game, when you click on a planet, you already see the name on the side. And you also see the name near the slots where you have to drag the celestial bodies to.
IMO the learning effect/fun would be a bit higher, if you were to not show the name of the planet in the information panel on the left side when clicking on it before being dragged to its correct slot. And once it is in the correct slot and then you click on it, then you should be able to see the name.

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/SortingPlanetsDragAndDrop.cs
> +            if (!isSnapped)
IMO you should also be able to see the planetInfoMessageText of the planet when clicking on it, even if it has already been snapped. That way, people would still be able to learn about the planets even after they solved the sorting game.

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Resources/MLG/laboratory.xml
> +			<German>Drücke die ENTER-Taste, um das Planeten System-Experiment zu starten.</German>
I think it should be Planetensystem-Experiment or Planetensystemexperiment.

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Resources/MLG/planetarySystem.xml
> +            <German>Kinematik</German>
"Kinematik" does not mean "kinematic sun", either it should only be "kinematic" and "kinematik"/"kinematisch", or also have German "kinematische Sonne" or something like that, depending on what it actually does?

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Resources/MLG/planetarySystem.xml
> +                <p>Newtons'law Of Universal Gravitation</p>
missing space between "Newton's" and "law"
also "of" should be lowercase

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Resources/MLG/planetarySystem.xml
> +                <p>Newtons Gesetz Der Universellen Gravitation</p>
I'm not a physician, but I think it's either called "Newtonsches Gravitationsgesetz", In case I am wrong, I think you'd have to write "Newtons Gesetz der Universellen Gravitation" (lowercase d in der)?

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Resources/MLG/planetarySystem.xml
> +                <p>Solarsystem</p>
I think there's a space between solar and system

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Resources/MLG/planetarySystem.xml
> +                <p>Our Solarsystem is a </p>
solar system*

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Resources/MLG/planetarySystem.xml
> +                <p>&lt;b&gt;Distance From Sun &lt;/b&gt;(10^6 km): </p>
Distance from Sun

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Resources/MLG/planetarySystem.xml
> +                <p>&lt;b&gt;Obliquity To Orbit: &lt;/b&gt;(degrees): </p>
to*

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Resources/MLG/planetarySystem.xml
> +                <p>&lt;b&gt;Mean Temperatur &lt;/b&gt;(degree C): </p>
Temperature*

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Resources/MLG/planetarySystem.xml
> +                <p>&lt;b&gt;Number Of Moons &lt;/b&gt;: </p>
of*

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Resources/MLG/planetarySystem.xml
> +                <p>Wenn du bereits alles erkundet hast klicke auf den PC-Bildschirm um mit dem Teleskop die Planeten im Weltall zu beobachten. </p>
I think missing comma after "Wenn du bereits alles erkundet hast,"

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/HideUI.cs
> +        public void ToggleHideUI(bool hide)
IMO toggle indicates it will be set to the opposite of the current status, so I'd suggest renaming it to `SetUIActive(bool active)`

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/HideUI.cs
> +                }
This is if else is rather redundant, you could just choose a variable `visible `or something and then call AnimationUI.SetActive(visible), PlanetInformationUI.SetActive(visible), toggleHideUI.isOn=!visible; or something
Or maybe just simply call `ToggleHideUI`

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/PlanetInfo.cs
> +                    break;
This switch statement is rather long, if not too much work, it would be great to make PlanetInfo a ScriptableObject, and then create an instance for every planet/celestial body.

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/PlanetRotation.cs
> +            planetRotationPerSecond = (360 / -planetInfo.rotationPeriod) * (ROTATION_PERIOD_SCALE_FACTOR / 50);
instead of ` / 50`, you should write `Time.fixedDeltaTime` I suppose, because maybe in the future we might choose a different FixedUpdate interval

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/PlanetaryController.cs
> +        //[SerializeField] private bool isSunKinematic = true;
if code is not needed, it can be deleted

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/PlanetaryController.cs
> +                            break;
do we need different skyboxes?

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/PlanetaryController.cs
This file is quite large and I'd suggest splitting some functionality up into different parts, see my comments below to get some suggestions how this may be done.

First of all, the code for the planetery system simulation, and for the sorting should all be in seperate files.

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/PlanetaryController.cs
> +        #endregion UIToggleButtons
I'd suggest removing all UI references in this PlanetaryController class. The reason is that if we might want to port this experiment to VR, it will be very difficult/cumbersome to do so. Ideally, we would be able to use this exact same script for a VR version as well, and just exchange the script that handles UI interaction. So there are multiple approaches to how this could be done. A way would be to fire UnityEvents and use those on a new PlanetarySimulationUiController

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/PlanetaryController.cs
> +        #endregion SortingGameSpawner
Put all Sorting game code in a separate class, could be called e.g. `PlanetSortingGameController`

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/PlanetaryController.cs
> +         */
btw, you can use 
```
        /// <summary>
        /// Method summary
        /// </summary>
        /// <param name="paramName">Parameter description</param>
        /// <returns>Return value description</returns>
```
then the description can also be used by the IDE more effectively

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/FlyCamera.cs
I'd suggest putting the FlyCamera script on the Camera, not on the Game Controller GameObject

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/FlyCamera.cs
> +            }
replace if else with
```
                Cursor.lockState = active ? CursorLockMode.Locked : CursorLockMode.None;
                Cursor.visible = !active;
```

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/FlyCamera.cs
> +        private void ToggleCameraControl(bool active)
toggle suggests current status is inverted, but you pass a parameter active, so I'd suggest renaming to SetCameraControlActive or something similar?

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/PlanetaryController.cs
> +        #endregion Trajectories
Probably would make sense to create a seperate script file for trajectories, maybe you can merge PlanetTrajectory with this code, let it inherit from MonoBehaviour.

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/PlanetaryController.cs
> +        #endregion UIToggleButtons
Maybe you can create a separate file for all UI logic of this script, so that this script becomes independent from the UI

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/PlanetaryController.cs
> +        #endregion StartScreenScenes
All the code that handles entering and exiting the sorting game or the planet simulation should be in a separate script file.

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Prefabs/PlanetsSolarSystem/6_Saturn Variant.prefab
I think Saturn has no rigidbody? Is this on purpose?

2024-09-18 12:14 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Prefabs/PlanetsSortingGame/0_SunSortingPlanet Variant.prefab
is it necessary to have separate prefabs for the Solar system simulation and the sorting game? E.g. maybe if one of them needs e.g. rigidbody and the other does not, maybe it could be added/removed via a script?

2024-10-04 11:15 UTC, Lowfi001 commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/PlanetaryController.cs
> +                            break;
i deleted them

2024-10-10 21:03 UTC, Lowfi001 commented on unity/Assets/Tests/EditModeTests/ContentValidation/PcSceneValidationTests.cs
> +        [SkipTestForScenesWithReason("PlanetarySystem", ReasonIntentionallyMissing)]
i had to use my own because i changed some things otherwise i had to edit the original prefab

2024-10-10 21:27 UTC, Lowfi001 commented on unity/Assets/Tests/EditModeTests/ContentValidation/PcSceneValidationTests.cs
> +        [SkipTestForScenesWithReason("PlanetarySystem", ReasonIntentionallyMissing)]
i wanted the helpi messages permanently otherwise they would be turned off when hiding the whole UI or the different UI windows of the game

2024-10-10 21:38 UTC, Lowfi001 commented on unity/Assets/Tests/EditModeTests/ContentValidation/PcSceneValidationTests.cs
> +        [SkipTestForScenesWithReason("PlanetarySystem", ReasonIntentionallyMissing)]
UI panels are used but deactivated at start which would fail the tests

2024-10-11 21:56 UTC, Lowfi001 commented on unity/Assets/Tests/EditModeTests/ContentValidation/PcSceneValidationTests.cs
> +        [SkipTestForScenesWithReason("Optics, PlanetarySystem", ReasonIntentionallyMissing)]
i had to use my own because i changed some things otherwise i had to edit the original prefab

2024-10-11 22:05 UTC, Lowfi001 commented on unity/Assets/Tests/EditModeTests/ContentValidation/PcSceneValidationTests.cs
> +        [SkipTestForScenesWithReason("Optics, PlanetarySystem", ReasonIntentionallyMissing)]
i had to use my own because i changed some things otherwise i had to edit the original prefab

2024-10-17 10:56 UTC, FlorianGlawogger requested changes
Hi, the code reworks are very cool, code looks now much cleaner and splitting up the code in parts was well done 👍 Thanks a lot for that! :) I just have a few more code suggestions, and took a closer look at some of the used assets (which I somehow overlooked in my last review, sorry about that); maybe also Michael can chime in with his expertise in case some comments are not clear/not useful

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/reusablePrefabs/experimentSetting/experimentRoom/Prefabs/PcTable.prefab
I think this could be made a prefab variant of Table.prefab

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/ProjectSettings/ProjectSettings.asset
could be reverted?

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Textures/ChartsAndScreens/planet_chart.png
these images are not translated in German, we should change that later on

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Textures/ChartsAndScreens/COLORSWATCH.jpg
is this needed?
Pretty sure we don't have the rights to add this to a public repository

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Sound/long_pop.wav
this is from Epic Stock Media, are we allowed to add this to a public repo?

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Sound/interface_hint_notification.wav
not sure where this sound is from, do we have the rights for it?

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Materials/planets/earth_2.mat
Not specific to just this file, but for all Earth materials:
Do we need 4 earth materials? seems like one would be enough? Please delete the unused ones

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Materials/planets/jupiter.mat
Not specific to just this file, but for all Planet materials: why are there materials for each planet in PlanetarySystem/Materials/planets/ but also in PlanetarySystem/Textures/SolarTextures/Materials 

please make sure to only have one material per planet

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Materials/trajectories/trajectory_0.mat
It's probably alright to leave it as it is, but it would have been nicer to just have one trajectory material, and the color of it is then changed via PlanetInformation ScriptableObject or something similar

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Materials/particleSystems/particle_0.mat
It's probably alright to leave it as it is, but it would have been nicer to just have one particle material, and the color of it is then changed via PlanetInformation ScriptableObject or something similar

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Materials/planet_placeholder.mat
should be in the planets folder

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Materials/sun_particles.mat
should be moved in the particle system folder

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/PlanetarySystem.pc.meta
please delete

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Prefabs/planet.prefab
is this file necessary? please delete if not

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Prefabs/SortingPlanet Variant.prefab
is this file necessary? please delete if not

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Resources/MLG/planetarySystem.xml
> +                <p>steuern.</p>
Related to most translations:
Is there a reason why you wrap text in `<p> </p>` tags? Just having one word per line sometimes seems a bit weird?

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Resources/MLG/planetarySystem.xml
> +                <p>zu den Himmelskörper genau durch. </p>
![grafik](https://github.com/user-attachments/assets/50addd54-367d-4c40-9442-56deb490d7b1)
line wrap after "Lies" seems weird?

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Textures/wall/grey_wall_disp_4k.png
not sure where this texture is from; and whether rights are okay?
Not sure tbh if a grey wall texture is even needed; The other experiments are set all in the same room more ore less; IMO it would be better if all rooms looked the same,

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/ProjectSettings/TagManager.asset
> +  - SortingGamePlanet
AFAIK the SortingGamePlanet tag is only used to get the initial planets at the start of the game, IMO there is no need to create a tag just for that purpose when you could also add a [SerializeField] array and initialize it via Unity inspector

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Prefabs/Sorting Minigame.prefab
Some of the prefab overrides of the sorting station are not useful;
e.g. planet rotation and planet info message text should be reverted to the prefab state of Sorting Station, as they are the same:
![grafik](https://github.com/user-attachments/assets/e81e87b3-d8b1-47d5-85ca-aaf433e57f6e)
(i.e. the only prefab override that probably makes sense is the SortingPlanetTarget, as that target doesn't exist in the SortingStation)
Please check the prefab overrides of the SortingStation for all the sorting planets

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/FlyCamera.cs
> +            float y = Input.GetAxis("Vertical") * mouseSpeed * Time.deltaTime;
usage of Time.deltaTime here;
if you change the time/Universe speed, this also changes how the camera behaves, please use Time.unscaledDeltaTime instead

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/FlyCamera.cs
> +            float mouseY = Input.GetAxis("Mouse Y") * mouseSensitivity * Time.deltaTime;
unscaleddeltatime

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Prefabs/Animation.prefab
IMHO animation is a name that is not worthy of your work, because it is essentially a simulation of the solar system, not just an animation; 
Also the name just being Animation (or just Simulation) isn't too great either; should be PlanetarySystemAnimation or PlanetarySystemSimulation (though if you rename to simulation, ensure to change the name everywhere, not just this prefab)

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Prefabs/Environment/SortingStationFilled.prefab
is this needed? Afaik it's only used in the planetarySystem.laboratoryBlock, and IMO you could use the SortingStation.prefab there as well maybe?

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Textures/ChartsAndScreens/start_animation.png
wouldn't it also be possible to use TextMeshPro labels instead of writing text on the texture? because TMP has the advantage that it's always as sharp as it needs to be, and it can easily be translated; also: if in the future we wanted to create e.g. a 3rd part of the PlanetarySystem experiment, then we wouldn't know which font to use for creating new textures for the new part of the experiment etc.

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/ProjectSettings/TagManager.asset
> +  - Planet
I don't think the "Planet" tag is used anywhere? please delete unused tags

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/ProjectSettings/TagManager.asset
> +  - OrientationGizmo
Is the orientationGizmo tag required anywhere? if not please delete it

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/StartScreenScenes.cs
> +            }
Could you maybe just call `LerpCameraToPosition(currentCamera, initialMainCamera, lerpDuration)` inside this method?

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Prefabs/Environment/SortingStation.prefab
this prefab does not actually contain the sorting planets prefabs? I.e. all the sorting planet prefabs are currently not in use anywhere I think?

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Prefabs/Environment/Interactable.prefab
Please rename to InteractablePlanetarySystemScreens or something

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/HideUI.cs
> +            //Debug.Log("HideUI: SetUIActive(active): " + active);
ahh, I think this might be because of my last PR comment, where I asked you to rename from ToggleHideUI to SetUIActive; 
However, in SetUIActive, you call `SetActive(!active)` this is a bit confusing
please either rename the bool active to bool hide or something again, or to call SetActive(active), and then have a seperate OnToggleUiChanged(bool shouldHide) method that is connected to the UI Toggle and then have it call SetUIActive(!shouldHide) ; but the first approach is less work I guess? sorry for being a bit confusing in my initial PR review

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/PlanetInfo.cs
> +            switch (PlanetInformationOf)
As discussed, switch is not the best solution, but if it's too much work to migrate to ScriptableObject this can stay 👍

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/PlanetSortingGameController.cs
> +        #endregion KeyInput
Replace` foreach switch if `thing with just `if (Input.GetKeyDown(KeyCode.L)) { }`

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/FBX/telescope/telescope.fbx
The telescope looks really good! However, ot has 27773 vertices, which is quite a lot for a background object. Do you think you could reduce the number of vertices? maybe try Decimate modifier, or some other approach; if it's too much work than I think it might also be alright as it is now

Also, could you clear "Sharp" where it's not needed, I think currently it's on every edge; Instead mark flat with Flat shading and smooth faces with smooth-shading
![grafik](https://github.com/user-attachments/assets/54f82ce6-e4de-4a69-9b9a-ad729f3e46bf)

Certain areas on the other hand should be shaded with smooth-shading, like this probably:
![grafik](https://github.com/user-attachments/assets/08008466-129a-4a64-b637-471d0010390f)

Also: see my comment regarding the COLORSWATCH file; if you dont have the rights for it there needs to be some material/color/uv mapping solution;, either you try to recreate the file, or you assign materials for each color to the telescope, or you go full out texture painting, there are probably multiple approaches how this could be solved

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/FBX/telescope/telescope_1_base.fbx
are the telescope_[1-6] fbx files needed if we already have the telescope.fbx base file?

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/PlanetarySystem.pc.unity
Many UI elements have some missing references to callbacks for events
e.g. OnValueChanged of the trajectory toggle
![grafik](https://github.com/user-attachments/assets/5df0109b-1012-4b98-a90f-f1f2210c8877)

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/PlanetTrajectoryController.cs
> +            }
Michael has the ultimate say on this, but IMO everything related to ParticleSystems that aren't being used can be deleted; would also improve performance a bit

2024-10-17 10:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/SortingPlanetsDragAndDrop.cs
> +
I think this method would be more suited to be in the planetary controller class

2024-10-18 09:44 UTC, Lowfi001 commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Sound/long_pop.wav
https://mixkit.co/free-sound-effects/pop/
Long pop
Free License https://mixkit.co/license/#sfxFree (Educational Purposes/ Video games)

2024-10-18 09:47 UTC, Lowfi001 commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Sound/interface_hint_notification.wav
https://mixkit.co/free-sound-effects/notification/
Interface hint notification
Free License https://mixkit.co/license/#sfxFree (Educational Purposes/ Video games)

2024-10-30 10:02 UTC, FlorianGlawogger requested changes
Hi, as always thanks for the improvements and implemented changes! e.g. you reduced the number of files quite a lot, which means less MB download for Maroon contributors/players down the line 👍 yay! I still found some things that I think should still be changed before merging the PR though
I think while renaming from animation to simulation you probably forgot to commit reference changes in the unity scene, thus now you cannot switch to the simulation part of your experiment, so this still needs to be fixed, otherwise people cannot access half your experiment 😅 ; otherwise I think it should be mostly small changes left, typos, some commented out Debug.Log lines that can be removed, and so on; 
Sorry for all the back-and-forth, I hope you're still understanding with the requested changes; looking forward to the last few changes and then finally merging this awesome new experiment 😃

2024-10-30 10:02 UTC, FlorianGlawogger commented on unity/Assets/Maroon/reusableGui/Menu/maroon-reel.renderTexture
not sure why this file has been changed?

2024-10-30 10:02 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/ChangeImageByLanguage.cs
> +                //Debug.Log("ChangeImageByLanguage(): ChangeImageLanguage(): should be DE " + lang);
comment could be removed

2024-10-30 10:02 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/ChangeImageByLanguage.cs
> +            //Debug.Log("ChangeImageByLanguage(): ChangeImageLanguage(): listener invoked with language: " + lang);
comment could be removed

2024-10-30 10:02 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/ChangeImageByLanguage.cs
> +                //Debug.Log("ChangeImageByLanguage(): ChangeImageLanguage(): should be ENG " + lang);
comment could be removed

2024-10-30 10:02 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Resources/MLG/planetarySystem.xml
>                  <p>zu den Himmelskörper genau durch. </p>
zu den Himmelskörpern* (missing n)

2024-10-30 10:02 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Resources/MLG/planetarySystem.xml
>                  <p>Probiere mit den verschiedenen Einstellungen auf der Seite herum: </p>
maybe "Probiere die verschiedenen Einstellungen auf der Seite aus"?

2024-10-30 10:02 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/FBX/telescope/planetary_system_telescope.fbx
![grafik](https://github.com/user-attachments/assets/76ec9274-45b5-4352-8fbb-a124392553dd)
Somehow this part of the telescope now has 44,000 vertices?


A few commits ago ( 989abde0013f47605f9587f99b20d797eb03673f ), that part only had 14,500 vertices, and the whole telescope had 27,773 vertices??
![grafik](https://github.com/user-attachments/assets/6e3d8fcd-e102-4de8-ad28-6a3d45ff874b)

2024-10-30 10:02 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/PlanetarySystem.pc.unity
missing callback on StartPlanetarySystemSimulationScreen
![grafik](https://github.com/user-attachments/assets/d7ed35ce-c27b-42b8-9ba5-7a9008b09a6e)
and StartPlanetarySystemSimulationScreenSortingGame
![grafik](https://github.com/user-attachments/assets/f77ff2a4-c2bc-492a-8692-ac0b70a49cd4)

2024-10-30 10:02 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Prefabs/PlanetarySystemSimulation.prefab
for me the simulation now looks like that:
![grafik](https://github.com/user-attachments/assets/16ba1eea-2e7a-4c8d-9ed9-14dae295db16)
not sure what went wrong here? no skybox, and planets seem to crash into the sun

2024-10-30 10:02 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/PlanetarySystem.pc.unity
![grafik](https://github.com/user-attachments/assets/f8696238-221a-467c-9b00-ab099fa91782)
various fields set to None (HideUI's UI, skybox material, simulation camera, start screen scenes)

2024-10-30 10:02 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/PlanetarySystem.pc.unity
![grafik](https://github.com/user-attachments/assets/e1627928-db97-40aa-b5d6-3776e55612c6)
when starting the simulation, the trajectories checkbox is OFF although you can see the trajectories, so the checkbox should be checked when starting the simulation

2024-10-30 10:02 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/PlanetarySystem.pc.unity
when resetting the simulation, certain things like kinematic sun are reset, but not their corresponding UI toggle/checkbox

2024-10-30 10:02 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/PlanetarySystem.pc.unity
I found a very weird bug, maybe you know more about it/how to fix it:
So usually, everything works fine; but if you start the PlanetarySystem.pc.unity scene with the Unity Editor (you have to start in that scene, if you start in e.g. bootstrapping scene, the bug is not reproducable), then go back to main menu, then re-enter the Planetary Simulation experiment; and then immediatelly I get tons of Errors for an invalid input force that's been trying to be assigned to rigidbodies:
```
rigidbody.force assign attempt for '6_saturn' is not valid. Input force is { NaN, NaN, NaN }.
UnityEngine.Rigidbody:AddForce (UnityEngine.Vector3)
Maroon.Experiments.PlanetarySystem.PlanetaryController:Gravity () (at Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/PlanetaryController.cs:281)
Maroon.Experiments.PlanetarySystem.PlanetaryController:FixedUpdate () (at Assets/Maroon/scenes/experiments/PlanetarySystem/Scripts/PlanetaryController.cs:90)
```
![grafik](https://github.com/user-attachments/assets/927674ec-fa25-4069-b3a1-ff8bf337734b)

(maybe look quickly into it, but If you cannot reproduce it, or don't know how to fix it, then just leave it as it is I guess, since it shouldn't occur in production anyways since we always start with bootstrapping?)

2024-10-30 10:02 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PlanetarySystem/Resources/PlanetarySystem.laboratoryblock.prefab
please add a collider to the sorting station table thing here

2024-10-31 10:39 UTC, FlorianGlawogger approved these changes
IMO ready to be merged 👍  
looks good, fun experiment, well done! :)

2024-11-02 08:35 UTC, michaelholly approved these changes

2024-11-02 08:37 UTC, michaelholly commented
@FlorianGlawogger please squash and merge it.

2024-11-06 08:30 UTC, merged