Feature/Maroon-455_OpticsExtension
GamesResearchTUG/Maroon pull request #477
Opened 2024-04-30 14:01 UTC by Xalos11

Finished implementation of extended physics optics experiment.

Closes #455

2024-05-07 08:16 UTC, michaelholly requested changes
Very nice implementation!

Please see the requested changes for merging the PR.
Also, check that all builds run successfully.
See: https://github.com/GameLabGraz/Maroon/actions/runs/8968850854

2024-05-07 08:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/HuygensPrinciple/materials/Grey.mat
> -    - _Metallic: 0
I think these changes were not made on purpose. Please revert them if this is the case.

2024-05-07 08:16 UTC, michaelholly commented on unity/ProjectSettings/EditorBuildSettings.asset
> -  - enabled: 1
Please revert these changes so the player can load the different scenes from the main menu.

2024-05-07 08:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/OpticsSimulations/Prefabs/ExperimentPreview/ExperimentPreview.prefab
These changes lead to a missing prefab reference in the Optics.laboratoryblock prefab resulting in an empty experiment station in the main laboratory room.
![image](https://github.com/GameLabGraz/Maroon/assets/11720008/6f9359a5-728f-47cb-b35f-c34c8a258995)

2024-05-07 08:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/OpticsSimulations/Prefabs/ExperimentPreview/TableObjectModels/objectFiles/preview_0.obj
Obj files cannot be imported. It seems that they are empty.

2024-05-07 08:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/OpticsSimulations/Prefabs/TableObject/OpticalComponent/WallObject.prefab
Is this table object still used? There is no entry in the dropdown menu to select it.

2024-05-07 08:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/OpticsSimulations/Prefabs/UI Elements/RotationArrowY.prefab
I am not sure if "UI Elements" is the correct folder name for these prefabs because they are not really UI elements. And the size of these arrows is a bit too big.

2024-05-07 08:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/OpticsSimulations/Optics.pc.unity
Please create a prefab for the OpticsExperiment that can be used later for other scenes.
The idea is to have one user interface independent experiment prefab that is used for the different platform scenes like PC, Web, and VR.
![image](https://github.com/GameLabGraz/Maroon/assets/11720008/8f16ca56-a283-49e8-ba24-a0d907d17b7c)

2024-05-07 08:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/OpticsSimulations/Resources/mlg/OpticsSimulations.xml
> -			<German>positiver-meniskus-Linse</German>
Consistent English/German upper/lower case.
Same for the next ones.

2024-05-07 08:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/OpticsSimulations/Sprites/refreshSymbol.png
Where is this used?
To be consistent with the framework you should use the bootstrap icons from https://icons.getbootstrap.com
see Maroon\Assets\Maroon\reusableImages

2024-05-07 08:16 UTC, michaelholly commented on unity/ProjectSettings/ProjectSettings.asset
Do we need these changes?

2024-05-07 08:16 UTC, michaelholly commented on unity/ProjectSettings/Packages/com.unity.services.core/Settings.json
empty file?

2024-05-07 08:16 UTC, michaelholly commented on unity/Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset
on purpose?

2024-05-07 08:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/OpticsSimulations/Scripts/old/DragLaserObject.cs
If the old scripts are no longer used, we can delete them.
Same for the others.

2024-05-07 08:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/OpticsSimulations/Scripts/old/Maroon.Experiments.OpticsSimulations.asmdef
Please create new assembly definition files for your script folders and add the dependencies accordingly.

2024-05-07 08:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/OpticsSimulations/Scripts/Camera/CameraControls.cs
> +namespace Maroon.scenes.experiments.OpticsSimulations.Scripts.Camera
Can we please move all namespaces  to "Maroon.Physics.Optics".
e.g. Maroon.Physics.Optics.Camera

2024-05-07 08:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/OpticsSimulations/Scripts/Camera/CameraControls.cs
> +        void Update()
use explicit private modifier

2024-05-07 08:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/OpticsSimulations/Scripts/Camera/CameraControls.cs
> +        public struct CameraSetting
Please move the struct definition to the top.

2024-05-07 08:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/OpticsSimulations/Scripts/Light/LightPath.cs
> +            switch (hitComponent.OpticalType)
I think we can convert this to:

`            
switch (hitComponent)
{
    case Wall wall:
        break;
    case Aperture aperture:
        break;
}
`

2024-05-07 08:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/OpticsSimulations/Scripts/Manager/ExperimentManager.cs
> +                Debug.LogError("SHOULD NOT OCCUR - Destroyed LightSourceManager");
LightSourceManager? Shouldn't it be ExperimentManager?

2024-05-07 08:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/OpticsSimulations/Scripts/Manager/LightComponentManager.cs
> +            Vector3 rotation = rot ?? new Vector3(0, 0, 0);
You can use Vector3.zero

2024-05-07 08:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/OpticsSimulations/Scripts/Manager/LightComponentManager.cs
> +            switch (nr)
using an enum and converting the integer would be nice.

2024-05-07 08:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/OpticsSimulations/Scripts/Manager/LightComponentManager.cs
> +            switch (nr)
I think we can define a read-only array for the wavelength settings and the integer nr as intex to select it from the array.

2024-05-07 08:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/OpticsSimulations/Scripts/Manager/OpticalComponentManager.cs
> +            Vector3 rotation = rot ?? new Vector3(0, 0, 0);
Vector3.zero

2024-05-07 08:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/OpticsSimulations/Scripts/Manager/OpticalComponentManager.cs
> +            switch (nr)
enum would be nicer

2024-05-07 08:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/OpticsSimulations/Scripts/Manager/PresetManager.cs
> +        public void Start()
why public?

2024-05-07 08:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/OpticsSimulations/Scripts/Manager/PresetManager.cs
> +            switch (nr)
enum would be nicer

2024-05-07 08:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/OpticsSimulations/Scripts/Manager/PresetManager.cs
> +        private void LensAndMirror()
later we could load these settings from a json file or something similar. also to support loading settings from Peters website via the WebGL receiver class.

2024-05-07 08:16 UTC, michaelholly commented on unity/Assets/Maroon/scenes/experiments/OpticsSimulations/Scripts/TableObject/Handlers/TranslationRotationHandler.cs
> +            _translationPlane = new Plane(transform.forward, new Vector3(0, 0, 0));
Vector3.zero

2024-05-07 11:09 UTC, Xalos11 commented on unity/Assets/Maroon/scenes/experiments/OpticsSimulations/Prefabs/TableObject/OpticalComponent/WallObject.prefab
Yes, it is only used as boundary so rays are not indefinitely long.

2024-05-08 08:11 UTC, michaelholly commented
There are still a few issues to be solved before merging the PR.

1. Builds are working, but unit tests fail
```
WhenClickLabCategoryGoToLabThenLoadScene(Physics` -> Lab) (2,614s)
---
Unhandled log message: '[Exception] MissingReferenceException: The object of type 'GameObject' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.'. Use UnityEngine.TestTools.LogAssert.Expect
---
```
2.  You should revert the EditorBuildSettings.asset to enable loading other scenes. Maybe this fix the EditMode test fails too.
3. The laboratory preview in the main lab room looks weird. The experiment preview prefab in the laboratory block should be next to the score view similar to the other experiment laboratory block prefabs

![image](https://github.com/GameLabGraz/Maroon/assets/11720008/dda97876-4bd6-47b3-b8c6-0260e806cf28)

2024-05-08 12:55 UTC, michaelholly approved these changes

2024-05-08 12:56 UTC, merged