Maroon-504 Updated NCalc package
GamesResearchTUG/Maroon pull request #505
Opened 2024-07-30 12:54 UTC by Averimon

Closes #504

2024-07-31 11:02 UTC, FlorianGlawogger requested changes
Seems to work fine, I think we should still include License files though?

2024-07-31 11:02 UTC, FlorianGlawogger commented on unity/Assets/Vendor/ncalc/LICENSE
why has the license file been removed?

2024-08-25 10:00 UTC, jonathanplatzer commented
When using this there is a regression in the Motion Solver, it seems like the newer versions of NCalc changed how functions and parameters are evaluated, so defining own functions like ``h(x): if(x == 0, 0.5, (1 + x/abs(x))/2)`` is broken, because variable shadowing doesn't work properly.

I need to investigate further how to solve this, maybe i have to rewrite some of the Motion Solver

2024-08-27 16:15 UTC, jonathanplatzer commented
I have found a solution to the regression, but I had to rework the `MotionEntity` class a little.
 
Do I just push the change to this branch or is there a different way this is normally done?

2024-09-05 18:52 UTC, jonathanplatzer commented
I pushed the fix for the regression and also restored the LICENSE file of NCalc, so this should be ready to be merged.

I tested it in the 3D Motion Simulation Experiment, as well as the rewritten CRT Experiment from #508 and everything works as expected again

2024-09-09 13:16 UTC, FlorianGlawogger approved these changes
Thanks a lot! License file is back again, and thanks for the rewrite of MotionEntity @jonathanplatzer , the new solution is also way more readable for the default t,x,y,z,vx,vy,vz dynamic parameters 👍 also good thing that you noticed the bug!

2024-09-09 13:22 UTC, merged