Feature/maroon 396 perlin noise experiment
GamesResearchTUG/Maroon pull request #507
Opened 2024-08-22 17:12 UTC by florianmarcher

Added perlin noise experiment

2024-09-09 12:56 UTC, FlorianGlawogger requested changes
Very awesome and fun new experiment! I really enjoyed playing around with the visualizations and all of the options. Really well done! The noise and visualization code works very well. Most of the comments are really just very nitpicky remarks regarding translations, some method names, namespace names, comments, etc. 
But to emphasize again: great work and amazing new experiment! 👍

2024-09-09 12:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/GlobalEntities/Management/SceneManager/SceneManager.prefab
![grafik](https://github.com/user-attachments/assets/e79bffaa-50b5-43c3-8765-36c37efcc180)
Probably a merge regression? There are now 2 "Computer Science" categories, one with Perlin Noise. There should only be one CS category.

Tests also fail because of this!

2024-09-09 12:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/reusableGui/Experiment/Scripts/Runtime/Tools/Charts/MutableLineChart.cs
> +        //I also didnt do a lot of testing so it might have some bugs
I think these comments could be removed IMO

2024-09-09 12:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/reusableScripts/Physics/Quantity/Quantity.cs
>                      onValueChanged?.Invoke(value);
According to the logic of SetVaApplyValueBounds, then `Invoke `should be called with `_value `instead of `value`;
however, this would likely break some parts of the code, see the comment below regarding default values of min and max

2024-09-09 12:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/reusableScripts/Physics/Quantity/Quantity.cs
> +        protected override int SetVaApplyValueBounds(int v) => Mathf.Clamp(v, minValue, maxValue);
min and maxValue don't have default values, e.g. in ColoumbsLaw experiment the currentMode quantity's min and max are not set. I think the experiment is still working because in the set the Invoke of onvaluechanged still uses the passed value instead of _value. 

(Best approach would probably to e.g. set min and max values of currentMode in ColoumbsLaw to 2 and 3 respectively)

2024-09-09 12:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/reusableScripts/Physics/Quantity/Quantity.cs
> +        protected override float SetVaApplyValueBounds(float v) => Mathf.Clamp(v, minValue, maxValue);
see comment regarding SetVaApplyValueBounds for QuantityInt

2024-09-09 12:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/reusableScripts/Physics/Quantity/Quantity.cs
> +        protected virtual T SetVaApplyValueBounds(T v) => v;
I am not sure about the naming. What does the "Va" stand for? Furthermore, the method name starts with Set, but does not actually set anything?

2024-09-09 12:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PerlinNoise/PerlinNoise.pc.unity
Is this button used anywhere?
![grafik](https://github.com/user-attachments/assets/56c95ae8-fb25-4352-a329-a61f9f161627)
if not please remove it

2024-09-09 12:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PerlinNoise/PerlinNoise.pc.unity
Not a big problem, but when using a somewhat narrow screen resolution, if you start dragging any of the sliders on the right-hand panel, (grab the slider knob if it's in the very left), then the Perlin Noise mesh also rotates with the slider dragging.

e.g. in this screen resolution:
![grafik](https://github.com/user-attachments/assets/32e3eba8-877d-4164-942b-b89916b36e7a)

2024-09-09 12:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PerlinNoise/Materials/WireframeShaded-Unlit.shader
> +Shader "PerlinNoise/Wireframe"
This is the only shader in the category "PerlinNoise", either I suggest moving the VertexColor shader also to PerlinNoise category, or I suppose it would be better to move this shader into the Custom category? What's your opinion about that?

2024-09-09 12:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PerlinNoise/Scripts/GraphRenderer.cs
> +namespace Maroon.scenes.experiments.PerlinNoise.Scripts
namespace should only be called `Maroon.ComputerScience.PerlinNoise`. Applies to the other scripts as well

2024-09-09 12:56 UTC, FlorianGlawogger commented on unity/Assets/Resources/MLG/perlinnoise.xml
> +            <English>Welcome! Here you can get to know how perlin noise works. Try out different types and experiment
Please remove the line break, otherwise formatting looks a bit weird.
![grafik](https://github.com/user-attachments/assets/1ec56d3b-d260-49bb-b1af-6fbf03283c9d)

2024-09-09 12:56 UTC, FlorianGlawogger commented on unity/Assets/Resources/MLG/perlinnoise.xml
> +            <German>Grösse</German>
Größe*

2024-09-09 12:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PerlinNoise/Resources/PerlinNoise.laboratoryblock.prefab
Helpy just says "EnterPerlinNoiseExperiment",
![grafik](https://github.com/user-attachments/assets/babd7a74-db5f-475e-aa67-8c2cf5f3b905)

instead it should say something like "press enter to enter start perlin noise experiment" like how the other experiments also do it:
![grafik](https://github.com/user-attachments/assets/e1ece671-ee66-424a-a925-22ffa018ee11)

2024-09-09 12:56 UTC, FlorianGlawogger commented on unity/Assets/Resources/MLG/perlinnoise.xml
> +        </Translation>
Not sure if this translation is actually used? If not please remove it

2024-09-09 12:56 UTC, FlorianGlawogger commented on unity/Assets/Resources/MLG/perlinnoise.xml
> +            </German>
please also remove here the line break.

2024-09-09 12:56 UTC, FlorianGlawogger commented on unity/Assets/Resources/MLG/perlinnoise.xml
> +            </English>
please also remove here the line break.

2024-09-09 12:56 UTC, FlorianGlawogger commented on unity/Assets/Resources/MLG/perlinnoise.xml
> +        </Translation>
Is this translation key used? if not please remove

2024-09-09 12:56 UTC, FlorianGlawogger commented on unity/Assets/Resources/MLG/perlinnoise.xml
> +            <English>Perlin Noise is a type of &lt;b>gradient noise&lt;/b> that can be used to create infinite continuous pseudo-random values. These values can be manipulated by the seed, scale or o
Very minor nitpicking:
*seed, scale, or octaves (missing comma)
and I think there should also be a comma after `scales the x-axis,` and before`and &lt;b>octaves&lt;/b> adds multiple layers of noise.`?

2024-09-09 12:56 UTC, FlorianGlawogger commented on unity/Assets/Resources/MLG/perlinnoise.xml
> +            <German>Perlin-Noise ist eine Art &lt;b>Gradientenrauschen&lt;/b>, das verwendet werden kann, um unendliche kontinuierliche Pseudozufallswerte zu erzeugen. Diese Werte können durch den Se
again very minor nitpicking:
`um unendliche, kontinuierliche Pseudozufallswerte` (missing comma)
`fügt mehrere Schichten Rauschen hinzu.` (add Rauschen, to explain what kind of Schichten, and also to be closer to the English text)

2024-09-09 12:56 UTC, FlorianGlawogger commented on unity/Assets/Resources/MLG/perlinnoise.xml
> +            <German>Typ</German>
What's your opinion on calling it "Visualization Type"?

2024-09-09 12:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PerlinNoise/Scripts/NoiseVisualisations/NoiseVisualisationTriangulation.cs
> +        [SerializeField] [Range(0, 0.2f)] private float thickness = 1;
Range is 0 to 0.2 but default value is 1?

2024-09-09 12:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PerlinNoise/Scripts/NoiseExperimentBase.cs
> +        [SerializeField] protected bool dirtyImmediate;
Is it necessary that these are `[SerializeField]` variables?

2024-09-09 12:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PerlinNoise/Scripts/NoiseExperimentBase.cs
> +        // Start is called before the first frame update
Comment could be removed

2024-09-09 12:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/PerlinNoise/Scripts/NoiseExperiment.cs
> +        // Update is called once per frame
comment could be removed

2024-09-09 12:56 UTC, FlorianGlawogger commented on unity/Assets/Maroon/reusableGui/Experiment/Scripts/Runtime/RadioButton.cs
i think a RadioButton class was very much overdue and needed! However, I am not sure if maybe it would've been easier to use Unity's Toggle with the checkbox removed and a ToggleGroup? Or easiest approach would be just disable the Interactable in the OnClick method?
So IMO the RadioButton script and prefab etc. could be deleted

2024-09-10 17:22 UTC, florianmarcher commented on unity/Assets/Maroon/GlobalEntities/Management/SceneManager/SceneManager.prefab
fixed

2024-09-11 11:38 UTC, FlorianGlawogger approved these changes
Looks good to me now! 👍

2024-09-11 11:42 UTC, merged