Feature/maroon 404 falling ball viscosimeter
GamesResearchTUG/Maroon pull request #511
Opened 2024-08-27 11:43 UTC by danielliegl

Close #404

2024-09-11 14:26 UTC, FlorianGlawogger requested changes
The experiment is really cool, and very well done! I think it is really well-suited to conduct experiments with it and actually learn about viscosity. 😄 
I made a lot of remarks but mostly about code formatting, naming of methods, missing namespaces etc., so the vast majority of comments will not take up lots of time.
Please also merge with develop branch.
But again: very cool experiment! 👍

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/FallingBallViscosimeter.vr.unity
![grafik](https://github.com/user-attachments/assets/38362d87-7416-4f36-90e5-da856e4b5d5b)
If VR is not supported for the experiment, please delete the scene

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Resources/FallingBallViscosimeter.laboratoryblock.prefab
Incorrect text in laboratory
![grafik](https://github.com/user-attachments/assets/c49f36f0-6cb1-4578-a58b-1d8f9cc5af03)
(missing translation in Assets/Resources/MLG/laboratory.xml probably)

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Resources/FallingBallViscosimeter.laboratoryblock.prefab
Colliders are too large / too many colliders
![grafik](https://github.com/user-attachments/assets/11b3e83a-fa40-41ee-9fa8-5de56d9ff557)
(only the table and info stand sign thing should have colliders)

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Resources/FallingBallViscosimeter.laboratoryblock.prefab
Please delete unnecessary Coulombs Law stuff from this experiment 
![grafik](https://github.com/user-attachments/assets/a162155f-92a1-46ff-89ca-87629cd8a941)

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Ball.cs
> +      Debug.Log("dynamic visc " + dynamic_viscosity);
please remove this Debug.Log

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/reusableFonts/calling-code/CallingCode-Regular SDF.asset
Not sure why this file has been changed?
But I don't think anything important changed, so either please roll back to develop for this file, otherwise should also just be fine I suppose

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/reusableGui/Menu/maroon-reel.renderTexture
Correct me if I'm wrong, but I don't think you need to change this file? please revert back to develop branch

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/reusableGui/Experiment/Scripts/Runtime/QuantityPropertyView.cs
> +            reset_slider.AllowReset = allowReset;
I think you should also just be able to call
`slider.AllowReset(allowReset);`
instead of those two lines

(But see the comment regarding allowRest in this class, so likely this should just be removed anyways)

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/reusableGui/Experiment/Scripts/Runtime/QuantityPropertyView.cs
> +        public bool allowReset = true;
Is it necessary to add this bool here? Also might lead to confusion in the future since it is only used for the Slider and not the other types of Quantity. I agree that it would be useful to have something like this, but then we'd need to make sure it works for all possibilities.

I just talked with Michael, and we agreed that it's probably the easiest to do it similarly like e.g. `PointWave_Selectionhandler.cs` does it by calling `waveSourceAmplitudeSlider.AllowReset(false);` in the code.

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/reusableMaterials/matGlass/Glass.mat
I think you changed the alpha and blue values of the material? 
please revert back to develop branch for this file, because many other scenes rely on this material, and then those all would look differently and that's not supposed to happen. (If you need your own glass material, you can copy it and place it in the Materials folder of your experiment)

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/reusablePrefabs/AdventureForge/Geometry/Industrial Cabinets and Shelves/MetalCabinet01/Materials/CleanRed/512/MetalCabinetSupportMA512.mat
I think you maybe enabled Emission by accident? Anyways, please revert back to develop

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/reusablePrefabs/AdventureForge/Geometry/Industrial Cabinets and Shelves/MetalCabinet01/Materials/MetalCabientCornersupportMA.mat
Please revert back to develop

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/reusablePrefabs/AdventureForge/Geometry/Industrial Cabinets and Shelves/MetalCabinet01/Materials/MetalCabinetBodyMA.mat
Please revert back to develop

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/reusablePrefabs/planet/Materials/Earth2kMaterial.mat
Please revert back to develop

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/reusablePrefabs/satellite/Materials/aluminum1.mat
Please revert back to develop

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/reusablePrefabs/satellite/Materials/dish_AO_01.mat
Please revert back to develop

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/reusablePrefabs/satellite/Materials/magelan_map1.mat
Please revert back to develop

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/reusablePrefabs/satellite/Materials/magelan_solar.mat
Please revert back to develop

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/reusablePrefabs/tugraz/materials/glass.mat
changed color of a shared material, Please revert back to develop

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/reusablePrefabs/vanDeGraaff/Materials/beige.mat
Please revert back to develop

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/reusableGui/Experiment/Scripts/Runtime/QuantityPropertyView.cs
> +                        decimalQuantity.Value = (decimal)value;
Is it necessary to have a QuantityDecimal if you use the float value of a Slider anyways? Because if you need higher precision for calculations you could still convert the QuantityFloat to e.g. decimal later in your calculations class. But you know the calculations part of the experiment better than I do, so please just let us know if/why you do need QuantityDecimal ^^
But as far as I can see it, you could use a Float quantity, and then cast it to decimal for your calculations?

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ViscosimeterManager.cs
> +      fluid_temperature_.maxValue = 100.0m;
I think this should be set in the Inspector 
EDIT: okay, just saw inspector doesn't support decimal property drawers, so if it stays at QuantityDecimal (see comment above) then it's fine, otherwise I'd suggest using in Inspector

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Sprites/ramanheadshot.jpg
Licensing rights for this image are fine?

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/reusableScripts/Tools/StopWatch/StopWatch.cs
> +        public QuantityFloat timeScale = 1;
Is this needed? If not please remove?

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/reusableScripts/Tools/StopWatch/StopWatch.cs
> +using Maroon.Physics;
If QuantityFloat below is to be removed, then please remove this as well.

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/FallingBallViscosimeter.pc/LightingData.asset
Regarding all files in this folder:
Did you force add these? Lighting data should be in .gitignore:
LightingData*
Lightmap*
ReflectionProbe*
*.lighting
*.lighting.meta

Thus I think this whole folder can be removed

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/FallingBallViscosimeter.vr/LightingData.asset
See comment for .pc light data, same applies here as well

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Meshes/pycnometer.fbx
Great mesh! Is there a reason though why you did not smooth-shade the faces though?
I think it would look even better with smooth shading, you can do it in e.g. Blender by right-clicking on a face in edit mode, and then press shade smooth
![grafik](https://github.com/user-attachments/assets/59d8d2f9-455a-4b74-a130-e7aa3708ee48)
but it's also fine how it looks now IMO

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Meshes/scale.fbx
Smooth shading could also be used on the "perimeter sides" of the metal part? :) (highlighted in yellow) But it's also fine how it looks now^^
![grafik](https://github.com/user-attachments/assets/d7955193-186f-49e9-957b-f6d9ec6dbac4)

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Prefabs/Caliper.prefab
Is the Measuring Tape script needed?
![grafik](https://github.com/user-attachments/assets/c8a93c39-cf1a-4a78-895a-f55bcdf45b3f)
I think it's always disabled, so probably can be removed

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Prefabs/Scale.prefab
Is this scale prefab used? because the scale in the experiment is not this prefab, so I think either this prefab should be deleted, or the actual scale should be this prefab and then used in the scene

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Prefabs/StopWatchViscosimeter.prefab
Would be cool if this was a PrefabVariant of the original StopWatch prefab
![grafik](https://github.com/user-attachments/assets/3eca59ad-5e47-4bb6-ae76-a9ec09f800e7)

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Prefabs/OilHeatingElement.prefab
Is this used? It's disabled in the experiment scene, if it's not used it should be deleted

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Resources/FallingBallViscometerExperimentScore.asset
> +  experimentName: Coulombs Law
Wrong name

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/FluidViscosityData.cs
> +        public string name;
hides the name property, 
![grafik](https://github.com/user-attachments/assets/8c90aa83-c730-4e62-a8d2-29f3b5252c33)
so probably should be renamed to something like "fluidName"?

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/FluidViscosityData.cs
> +        public Color fluid_color;
I think this is never used? Would definitely be very awesome if it was used though 👍

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Resources/FluidData/Water.asset
> +  name: Water
Problem is if German language is used, then it's still called "Water", a solution to this would be to store an MLG key here (rename name property accordingly to e.g. fluidNameTranslationKey or something) and then let the MLG localization translate the name accordingly.

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/CameraControls.cs
> +    // Update is called once per frame
default comment can be removed

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/CameraControls.cs
> +public class CameraControls : MonoBehaviour
missing namespace

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/CameraControls.cs
> +    private float rotationSpeed = 500f;
never used

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/CameraControls.cs
> +using System.Collections.Generic;
unnecessary usings

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/CameraControls.cs
> +    void Update()
method could be made `private` i suppose

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/CameraControls.cs
> +    void Zoom(bool zoomIn)
can be made `private`

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/DragDrop/DragDrop.cs
> +      //}
please remove

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/DragDrop/DragDrop.cs
> +using System.Collections.Generic;
unnecessary usings

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/DragDrop/DragDrop.cs
> +using UnityEngine.Purchasing;
unnecessary usings

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/DragDrop/DragDrop.cs
> +  public bool enabled = true;
hides inherited member `enabled`, please use a different name

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/DragDrop/DragDrop.cs
> +public class DragDrop : MonoBehaviour
missing namespace here as well, please use the namesace e.g. Maroon.Physics.Viscosimeter or something like that for all scripts

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts.meta
Please add an assembly definition to the FallingBallViscosimeter/Scripts folder (you can look at other experiments like CoulombsLaw to see how they used/named the AssemblyDefinition)

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/DragDrop/DragDrop.cs
> +  Plane plane;
could be made `private`

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/DragDrop/DragDrop.cs
Please also use 4 spaces in this file for indentation, like in the rest of Maroon code

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/DragDrop/DragDrop.cs
> +      dragEndedCallback(this);
This is a valid approach to handle snapping, but IMO the name dragEndedCallback suggests that it is always called when dragging ends, even for GameObjects that do not have snap set to true. Thus I would suggest renaming it to something like `dragEndedSnapCallback`?

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/DragDrop/SnapController.cs
> +public class SnapController : MonoBehaviour
missing namespace

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/DragDrop/SnapController.cs
> +using System.Collections;
unnecessary using

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/DragDrop/SnapController.cs
> +    // Start is called before the first frame update
Please remove

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/DragDrop/SnapController.cs
> +
Please remove those 2 empty lines

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/DragDrop/SnapPoint.cs
> +public class SnapPoint : MonoBehaviour
missing namespace

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Ball.cs
> +namespace Maroon.Physics
Please use a namespace with something like Maroon.Physics.Viscosimeter or something

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Ball.cs
> +using UnityEngine.Purchasing.Extension;
unnecessary using

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Ball.cs
> +using System.Collections.Generic;
unnecessary usings

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Ball.cs
> +    private bool dropped_ = true;
I think this variable is never used?

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Ball.cs
> +    private decimal buoyancy_force_ = 0.0m;
I think these 2 variables are never used?

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Ball.cs
please also here use 4 spaces for indentation

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Ball.cs
> +      radius_ = start_diameter_ / 2000m;
apparently, start_diameter is in mm and radius is in m? What do you think about naming the variable radius_in_m and diameter_in_mm or something similar to avoid future confusion?

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Ball.cs
> +    }
I think unnecessary and could be removed

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Ball.cs
> +      //updateBall();
can be removed?

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Ball.cs
> +    decimal calculateVolume()
could be made private?

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Ball.cs
> +      //rigidbody_.velocity = Vector3.zero;
could be removed?

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Ball.cs
> +    public void dropBall()
please start method names with a capital letter

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Ball.cs
> +        touching_oil = true;
if I understand correctly, then the variable `touching_oil`, refers to touching liquid / touching fluid? if so then please rename variable accordingly

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Ball.cs
> +    void ApplyFallPhysics()
please make `private`

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Ball.cs
> +    void ApplyForce(decimal force)
please make `private`

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Ball.cs
> +    bool CheckCollision(Vector3 position, decimal velocity)
please make `private`

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Ball.cs
> +    float GetPossibleMovement(Ray ray, float range)
please make `private`

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Pycnometer.cs
> +namespace Maroon.Physics
see above, use visco something namespace

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Pycnometer.cs
> +    void Start()
could be made private I suppose

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Pycnometer.cs
> +    // Start is called before the first frame update
can be removed

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Pycnometer.cs
> +    }
please remove

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Pycnometer.cs
> +    public void fillPycnometer() //kg/m^3
capitalize starting letter

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Pycnometer.cs
> +    public void emptyPycnometer()
capitalize starting letter

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Pycnometer.cs
> +      renderer_.material.color = new Color(0.3f, 0.3f, 0.3f, 0.3f);
would be cool if color was the Fluid color (specific to each fluid)

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Pycnometer.cs
use 4 space indentation

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Scale.cs
> +namespace Maroon.Physics
namespace
(and please insert blank line above)

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Scale.cs
use 4 space indentation

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Scale.cs
> +using System.Collections.Generic;
unnecessary usings

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Scale.cs
> +    // Start is called before the first frame update
remove

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Scale.cs
> +    }
I think it should be possible to just write
```
public void ResetObject()
{
}
```

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Scale.cs
> +    // Update is called once per frame
remove comment, could be made private

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Scale.cs
> +    void Awake()
could be made private

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Scale.cs
> +    void updateText()
capital starting letter, private

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/WeighableObject.cs
> +public class WeighableObject : MonoBehaviour, IResetObject
missing namespace

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/WeighableObject.cs
> +using System.Collections.Generic;
unnecessary usings

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/WeighableObject.cs
> +    public void resetWeight()
start with capital letter

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/WeighableObject.cs
> +    public void setWeight(decimal new_weight)
start with capital letter

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/WeighableObject.cs
> +    public decimal getWeight()
start with capital letter

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/WeighableObject.cs
> +    }
could be converted into a C# property

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Faucet.cs
> +public class Faucet : MonoBehaviour
namespace

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Faucet.cs
> +using System.Collections.Generic;
remove usings not needed

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Faucet.cs
> +    }
remove

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Faucet.cs
> +        _pycnometer = snapPoint.currentObject.gameObject.GetComponent<Pycnometer>();
throws NullReferenceException if snapPoint is empty

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurableObject.cs
> +using System.Collections.Generic;
remove

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurableObject.cs
> +namespace Maroon.Physics
namespace naming

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurableObject.cs
> +    private float length_;
don't think these are needed

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurableObject.cs
> +    void Start()
remove comment + make private

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurableObject.cs
> +      if(measuredAxis == null)
enum cannot be null, the default value is 0 I think, so this if is unnecessary

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurableObject.cs
use 4 space indentation

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurableObject.cs
> +    public void setChooseable(bool chooseable)
capital starting letter? 🥺

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurableObject.cs
> +    private void makeChooseable()
capital starting letter? 🥺 🥺

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurableObject.cs
> +    private void makeNotChooseable()
capital starting letter? 🥺 🥺  🥺

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurableObject.cs
> +    private void setDragDrop(bool active)
capital starting letter? 🥺 🥺 🥺🥺

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurableObject.cs
> +    }
please merge these 3 methods into 1, just have SetChooseable and then just clickable = chooseable; and SetDragDrop(!choosable); or something

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurableObject.cs
> +        Debug.Log(dragDrop.enabled);
can this be removed?

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurableObject.cs
> +    }
please remove

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurableObject.cs
> +      Debug.Log("Clicked this Boy");
Please remove this boy

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurementBox.cs
> +namespace Maroon.Physics
use visco something namespace

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurementBox.cs
> +using System.Collections.Generic;
please remove unnecessary usings

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurementBox.cs
> +    void toggleMeasurement(bool mode)
capitalize starting letter

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurementBox.cs
> +    }
remove

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurementManager.cs
> +    private float minSize = 0.1f;
can these be removed?

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurementManager.cs
indentation

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurementManager.cs
> +using System.Collections;
remove

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurementManager.cs
> +namespace Maroon.Physics
namespace naming

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurementManager.cs
> +using Object = UnityEngine.Object;
can be removed if you just call FindObjectsOfType<MeasurableObject>(); in geAllMeasurableObjects (without the Object.)

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurementManager.cs
> +
remove

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurementManager.cs
> +    void startMeasuringMode()
private + capital

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurementManager.cs
> +    public void endMeasuringMode()
capitalize starting letter

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurementManager.cs
> +    void fitObjectToCamera()
capitalize starting letter, private

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurementManager.cs
> +    public void chooseMeasuredObject()
capitalize starting letter

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurementManager.cs
> +    private void setAllChooseable(bool chooseable)
capitalize starting letter

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurementManager.cs
> +    public void setChosenObject(MeasurableObject mObject)
capitalize starting letter

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurementManager.cs
> +    }
remove

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurementManager.cs
> +    void getAllMeasurableObjects()
capitalize starting letter

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurementManager.cs
> +      measurementState = MeasurementState.Off;
could some parts of start and endMeasuringMode methods be grouped into one method that get's passed a parameter? e.g. parts of camera enabling/disabling stuff looks pretty similar

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurementManager.cs
> +
please remove these 3 empty lines

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/Caliper/Caliper.cs
> +    // Start is called before the first frame update
remove comment, make method private?

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/Caliper/Caliper.cs
> +
please remove these

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/Caliper/Caliper.cs
> +public class Caliper : MonoBehaviour
missing namespace

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/Caliper/Caliper.cs
I think this whole script can be deleted, as no variable/method is used?

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/Caliper/CaliperRenderer.cs
I think this script is never used and could thus be removed?

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/Caliper/MeasuringTape.cs
> +using System.Linq;
unnecessary usings

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/Caliper/MeasuringTape.cs
> +    [SerializeField]private float measuredLength;
please add a space between [SerializeField] and private

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/Caliper/MeasuringTape.cs
> +    [SerializeField]private DragDrop hook_dnd;
please add a space between [SerializeField] and private

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/Caliper/MeasuringTape.cs
> +    [SerializeField] private float offset;
please name this a bit more distinctive, what offset?

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/Caliper/MeasuringTape.cs
> +    void Update()
remove comment, make private

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/Caliper/MeasuringTape.cs
> +    void updateText()
make private, capitalize first letter

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/Caliper/MeasuringTape.cs
> +        positions = new Vector3[2];
I think this line could be removed if you just write `private Vector3[] positions = new Vector3[2];` when declaring the array

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/Caliper/MeasuringTape.cs
> +            offset = -0.03745f;
Is it necessary that it's -0.03745f and not -0.0375f ? because if not it could be simplified with the offset if (transform.rotation.z != 0f)

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/Caliper/MeasuringTape.cs
> +        if (transform.rotation.z != 0f)
didn't look into this a lot, but are you using the z of the Quaternion on purpose? I.e. usually when writing similar code I check the euler angles z, not the quaternion z

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Prefabs/MeasuringTape.prefab
I cannot move the type when dragging the white center cylinder part of the tape

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/OilHeatingElement/HeaterButton.cs
> +    private Material _material;
can be removed

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/OilHeatingElement/HeaterButton.cs
> +public class HeaterButton : MonoBehaviour
namespace missing

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/OilHeatingElement/HeaterButton.cs
> +using UnityEngine.Events;
remove not required usings

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/OilHeatingElement/HeaterButton.cs
> +    void Start()
remove comment and make private

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/OilHeatingElement/HeaterButton.cs
> +    }
remove

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/OilHeatingElement/HeaterButton.cs
> +    public void turnOff()
capital letter start

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/OilHeatingElement/OilHeatingElement.cs
> +using System.Collections.Generic;
remove

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/OilHeatingElement/OilHeatingElement.cs
> +public class OilHeatingElement : MonoBehaviour
no namespace

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/OilHeatingElement/OilHeatingElement.cs
> +    public static OilHeatingElement Instance;
Is it necessary this is a Singleton? Seems not like a usual use case for singleton to me from a quick glance?

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/OilHeatingElement/OilHeatingElement.cs
> +    [SerializeField]private float heatingSpeed = 0.1f;
add space after [SerializeField]

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/OilHeatingElement/OilHeatingElement.cs
> +    // Start is called before the first frame update
remove comment and make method private

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/OilHeatingElement/OilHeatingElement.cs
> +    void Update()
remove comment, make method private

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/OilHeatingElement/OilHeatingElement.cs
> +    }
I'd suggest renaming to ToggleHeating/Cooling, as that name makes it IMO a bit more clear, and using proerties to switch off cooling when heating and the other way around, something like:
```


    public bool Heating
    {
        get { return heating; }
        set { 
            heating = value;
            if (Heating)
                Cooling = false;
        }
    }

    public bool Cooling
    {
        get { return cooling; }
        set
        {
            cooling = value;
            if (Cooling)
                Heating = false;
        }
    }

    public bool ToggleHeating()
    {
        Heating = !Heating;
        return Heating;
    }

    public bool ToggleCooling()
    {
        Cooling = !Cooling;
        return Cooling;
    }
```

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/UI/Stopwatch/StopWatch.cs
is this script used? if not please delete

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/UI/Stopwatch/StopWatchStartButton.cs
> +public class StopWatchStartButton : MonoBehaviour
namespace

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/UI/Stopwatch/StopWatchStartButton.cs
> +using System.Collections.Generic;
remove

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/UI/Stopwatch/StopWatchStartButton.cs
> +    [SerializeField]private SimulationStartButton simStartButton;
add space after [serializefield]

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/UI/Stopwatch/StopWatchStartButton.cs
> +    void Start()
remove comment and private

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/UI/Stopwatch/StopWatchStartButton.cs
> +    void Update()
remove comment and private

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/UI/Stopwatch/StopWatchStartButton.cs
> +        text = gameObject.transform.Find("Text (TMP)").GetComponent<TMP_Text>();
gameObject.GetComponentInChildren should work

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/UI/Stopwatch/StopWatchStartButton.cs
> +        Debug.Log(text.text);
debug.log can be removed probably?

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/UI/Stopwatch/StopWatchStartButton.cs
Once the ball has been dropped, the countdown text still says "3", although it then should be disappear IMO

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/UI/Stopwatch/StopWatchStartButton.cs
> +                hover_timer = hover_timer + Time.deltaTime;
use += operator, and I'd suggest using Time.unscaledDeltaTime to avoid waiting very long when using slow mo

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/UI/Stopwatch/StopWatchStartButton.cs
> +                simStartButton.StartSimulation();
I think you could also just call 
            SimulationController.Instance.StartSimulation();
then you don't need the simStartButton variable

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Weighable.cs
can be removed I guess?

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Sprites/Materials/Vernier_Caliper_Stick.mat
I think this would be better placed in FallingBallViscosimeter/Materials

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Sprites/Materials.meta
if empty, can be removed

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ViscosimeterManager.cs
> +using Object = UnityEngine.Object;
can be removed when using GameObject. instead probably

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ViscosimeterManager.cs
> +using PlatformControls.PC;
remove unnecessary usings (System.Collections and Platformcontrols.PC)

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ViscosimeterManager.cs
> +namespace Maroon.Physics
use your own more specific namespace for the experiment

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ViscosimeterManager.cs
> +    public static float inaccuracyRange = 0.1f;
only used in this class, doesn't need to be public

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ViscosimeterManager.cs
> +    public QuantityDecimal fluid_temperature_ = 25.0m;
like mentioned above, does this need to be decimal?
you could just cast to decimal when using it

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ViscosimeterManager.cs
use 4 space indentation

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ViscosimeterManager.cs
> +    MeasurableObject currentMeasurableObject;
not needed?

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ViscosimeterManager.cs
> +    private Rigidbody _rigidbody;
not needed?

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ViscosimeterManager.cs
> +    private void prepareFluids()
capitalize letter starting

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ViscosimeterManager.cs
> +        _fluid_dropdown.options.Add(new TMP_Dropdown.OptionData() {text=fluid.name});
text should be localized using the LanguageManager

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ViscosimeterManager.cs
> +    public decimal calculateDynamicViscosity(decimal temperature)
please capitalize starting letter of method name

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ViscosimeterManager.cs
> +    public decimal celsiusToKelvin(decimal celsius)
please capitalize starting letter of method name

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ViscosimeterManager.cs
> +    void calculateFluidDensity()
please capitalize starting letter of method name, can this be made private? if not, public

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ViscosimeterManager.cs
> +      //fluid_density_ = (FluidTemperature * -0.37m + 891.83m); //kg/m^3
remove old code comment

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ViscosimeterManager.cs
> +    public void togglePycnometerFill(bool fill)
please capitalize starting letter of method name

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ViscosimeterManager.cs
> +    private void toggleMeasurementBoxes(bool mode)
please capitalize starting letter of method name

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ViscosimeterManager.cs
> +    void getAllMeasurableObjects()
please capitalize starting letter of method name, private

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ViscosimeterManager.cs
> +    // Update is called once per frame
remove

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ViscosimeterManager.cs
> +      //ball.updateBall();
remove commented out code

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ViscosimeterManager.cs
> +    void update_debug_text()
please capitalize starting letter of method name, and don't use underscore, use PascalCase

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ViscosimeterManager.cs
> +    public static float addInaccuracy(float input)
please capitalize starting letter of method name

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ViscosimeterManager.cs
> +    public static decimal addInaccuracy(decimal input)
please capitalize starting letter of method name

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ViscosimeterManager.cs
> +    }
if not needed, please remove

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/FallingBallViscosimeter.pc.unity
Missing Reference: FluidDropDown item
![grafik](https://github.com/user-attachments/assets/c21a9dea-f5a8-4d61-bc67-666719c719e3)
 
(You can use Tools -> MissingReferenceFinder to find missing references, tests require you to have no missing references)

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/FallingBallViscosimeter.pc.unity
Tooltips are not localized
![grafik](https://github.com/user-attachments/assets/b8b0c30c-7ccf-495e-9a38-e9f668b7872c)

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/FallingBallViscosimeter.pc.unity
When moving the pycnometer out of frame, I can never get it back, it should be returned to the starting pos when resetting simulation IMO

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/FallingBallViscosimeter.pc.unity
Very nitpicky remark, but IMO the picture frames are a bit distracting for the ball camera, 
![grafik](https://github.com/user-attachments/assets/9b0769ba-3d77-499d-be0d-3692c6b180b6)

maybe they could be moved out of the way a bit, like so (though maybe a bit nicer arranged):
![grafik](https://github.com/user-attachments/assets/09e61a8d-4c45-495d-b63e-089c8a28253a)
![grafik](https://github.com/user-attachments/assets/750c4d12-0652-437d-8a04-fb1fd97fc2b6)

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/FallingBallViscosimeter.pc.unity
When using any fluid other than 1,2-Ethanediol, (e.g. Cyclohexane), then the ball jumps up and down at the bottom of the cylinder tube
![cursor](https://github.com/user-attachments/assets/ae959b81-9904-4743-855e-9ff7b4f7a0ab)

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/FallingBallViscosimeter.pc.unity
not too big of a deal i suppose, but when the ball rotates, the ball camera rotates as well

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/FallingBallViscosimeter.pc.unity
When placing the ball, I often placed it to the Faucet snap point by accident
![grafik](https://github.com/user-attachments/assets/c4e9294d-936e-4c47-bc53-0ff22c2861dd)
Then the ball was outside the tube, but it still behaved (falling speed) the same as inside the tube filled with fluid
if it's not too much work it would be cool to prevent the ball from snapping to this snap point

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/FallingBallViscosimeter.pc.unity
Is it on purpose that the tooltip for the tube only appears above and below the red lines? (not in the center)

2024-09-11 14:26 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/FallingBallViscosimeter.pc.unity
When clicking Measure Length and then on e.g. the tube, I get the following error
![grafik](https://github.com/user-attachments/assets/ec1e5fb1-6e32-452d-b9da-b067858e09cb)

2024-10-01 14:41 UTC, danielliegl commented on unity/Assets/Maroon/reusableGui/Experiment/Scripts/Runtime/QuantityPropertyView.cs
> +        public bool allowReset = true;
I removed what I added in this class, and did it like the Point Wave experiment.

2024-10-01 14:55 UTC, danielliegl commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Sprites/ramanheadshot.jpg
Changed the image and added LICENCE.md with license information about the image in the folder

2024-10-01 15:17 UTC, danielliegl commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/DragDrop/DragDrop.cs
> +public class DragDrop : MonoBehaviour
i think i moved everything into that namespace now :)

2024-10-01 15:35 UTC, danielliegl commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Ball.cs
> +    }
needs the empty `HandleUpdate` because of it being a `PausableObject`

2024-10-01 15:38 UTC, danielliegl commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ExperimentObjects/Pycnometer.cs
> +      renderer_.material.color = new Color(0.3f, 0.3f, 0.3f, 0.3f);
i tried to do that, but these fluids are all colourless and transparent

2024-10-01 16:43 UTC, danielliegl commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurableObject.cs
> +      Debug.Log("Clicked this Boy");
rip boy

2024-10-01 16:44 UTC, danielliegl commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurementBox.cs
> +    void toggleMeasurement(bool mode)
removed, was not needed

2024-10-01 16:59 UTC, danielliegl commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/Caliper/MeasuringTape.cs
> +            offset = -0.03745f;
can be the same for both

2024-10-01 17:02 UTC, danielliegl commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/Caliper/MeasuringTape.cs
> +        if (transform.rotation.z != 0f)
it works with both, did'nt put much thought into that. i changed it to euler angles.

2024-10-01 17:04 UTC, danielliegl commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/OilHeatingElement/HeaterButton.cs
> +    private Material _material;
deleted this script, was unused

2024-10-01 17:04 UTC, danielliegl commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/Tools/OilHeatingElement/OilHeatingElement.cs
> +using System.Collections.Generic;
deleted this script, was unused

2024-10-01 17:08 UTC, danielliegl commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/UI/Stopwatch/StopWatchStartButton.cs
> +                hover_timer = hover_timer + Time.deltaTime;
ah nice, didn't know that unscaledDeltaTime existed. that fixes that waiting issue thanks

2024-10-01 17:34 UTC, danielliegl commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/FallingBallViscosimeter.pc.unity
made this snap point only available to the pycnometer

2024-10-01 17:41 UTC, danielliegl commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/FallingBallViscosimeter.pc.unity
freezed rotation of the ball

2024-10-02 08:07 UTC, danielliegl commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Meshes/pycnometer.fbx
smoothed that mesh :)

2024-10-02 08:09 UTC, danielliegl commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Meshes/scale.fbx
tried the same as the pycnometer here but got weird visual bugs, so i kept it as is

![grafik](https://github.com/user-attachments/assets/bb843d25-1a70-4786-a67b-68bf2b8951f3)

smooth scale is too powerful for maroon it seems

2024-10-02 10:00 UTC, danielliegl commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/FallingBallViscosimeter.pc.unity
i wrote a LocalizedSimpleTooltip component. Just need to know where to actually put the code. It's currently in the Scripts/UI folder of my Experiment. This should probably be somewhere, where it makes more sense?

2024-10-09 09:44 UTC, FlorianGlawogger commented
Hi, just to be sure we are on the same page @danielliegl , you requested another review, and I saw you made tons of requested changes! Though I looked at a few of the previous review's comments, and it seems like some of the comments are not resolved yet, e.g.  `Debug.Log("dynamic visc " + dynamic_viscosity);` is still in the Ball.cs file, or not sure if you wrote somewhere regarding the Decimal Quantity?
Please tell me in case I am missing something, but otherwise please make sure to resolve all suggestions before requesting another review to save us both some time, (or please write a comment in case a suggestion doesn't make sense).

2024-10-18 07:42 UTC, danielliegl commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Prefabs/Scale.prefab
removed.

2024-10-18 08:10 UTC, danielliegl commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/FluidViscosityData.cs
> +        public Color fluid_color;
i think you talk about the color here? was planned, but all liquids were colourless and clear, so i scrapped the idea. removed the color property

2024-10-18 08:32 UTC, danielliegl commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurementManager.cs
> +      measurementState = MeasurementState.Off;
combined into a single method: public void ToggleMeasuringMode(bool isMeasuring)

2024-10-18 08:36 UTC, danielliegl commented
> Hi, just to be sure we are on the same page @danielliegl , you requested another review, and I saw you made tons of requested changes! Though I looked at a few of the previous review's comments, and it seems like some of the comments are not resolved yet, e.g. `Debug.Log("dynamic visc " + dynamic_viscosity);` is still in the Ball.cs file, or not sure if you wrote somewhere regarding the Decimal Quantity? Please tell me in case I am missing something, but otherwise please make sure to resolve all suggestions before requesting another review to save us both some time, (or please write a comment in case a suggestion doesn't make sense).

Hi @FlorianGlawogger,
I guess I got sloppy after going through these 200 conversations, sorry. I went through all of them again. Now all issues that I have fixed are resolved. There is only the question about the Localization of the Tooltips.

2024-10-23 08:39 UTC, FlorianGlawogger requested changes
Awesome changes 👍  just found one more small bug, and a few nitpicks regarding some code formatting, but I think you will be able to fix those issues very quickly, and then we can finally merge this PR :)

2024-10-23 08:39 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/FallingBallViscosimeter.pc.unity
When placing the pycnometer flask on the scale, then pressing the reset simulation button, the scale still displays the weight of the pycnometer

2024-10-23 08:39 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/MeasurementBox.cs
please also use 4 space indentation here

2024-10-23 08:39 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ViscosimeterManager.cs
>  using Object = UnityEngine.Object;
I think you can remove this if you apply the suggestion below for the `GetAllMeasurableObjects` method

2024-10-23 08:39 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ViscosimeterManager.cs
> +            Object[] foundObjects = FindObjectsOfType<MeasurableObject>();
```
           MeasurableObject[] foundObjects = FindObjectsOfType<MeasurableObject>();

            measurableObjects = new List<MeasurableObject>();

            foreach (MeasurableObject obj in foundObjects)
            {
                measurableObjects.Add(obj as MeasurableObject);
            }
```
then we can get rid of using Object = UnityEngine.object at the start of the class

2024-10-23 08:39 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ViscosimeterManager.cs
> +        void UpdateDebugText()
please make private if possible

2024-10-23 08:39 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/ViscosimeterManager.cs
> +        void FixedUpdate()
please make private if possible

2024-10-23 08:47 UTC, FlorianGlawogger requested changes
just talked with Michael regarding the localized tooltip file, he made a suggestion where to place it.

2024-10-23 08:47 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/UI/LocalizedSimpleTooltip.cs
> +namespace GEAR.Localization.Text
change to `namespace Maroon.UI`

2024-10-23 08:47 UTC, FlorianGlawogger commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/Scripts/UI/LocalizedSimpleTooltip.cs
Please move file to reusableGUI experiment runtime scripts folder 
![grafik](https://github.com/user-attachments/assets/85db62e1-4def-467c-9c14-327d82448bff)

2024-10-23 13:00 UTC, danielliegl commented on unity/Assets/Maroon/scenes/experiments/FallingBallViscosimeter/FallingBallViscosimeter.pc.unity
fixed

2024-10-23 13:19 UTC, danielliegl commented
Fixed the last few things. Also fixed another bug, where the "Choose your object to measure" textbox stayed visible, after stopping measurement and added translations for the explanations of the measurement mode.

I hope this should be it :)

2024-10-23 13:59 UTC, FlorianGlawogger approved these changes
Looks good to me! 
Thanks for integrating all the feedback, and for adding a cool new experiment to Maroon 👍 🥳

2024-10-23 14:03 UTC, FlorianGlawogger commented
fyi: just waiting for Github Actions to finish, then we can merge it

2024-10-23 15:08 UTC, merged