Maroon-556 Add AssetResaver Editor script
GamesResearchTUG/Maroon pull request #557
Opened 2024-11-14 09:10 UTC by FlorianGlawogger

Close #556 
Editor script can be used after a Unity update where serialization changes, results in typical PRs not changing 1000 lines of code because they touched a scene.

2025-02-11 13:04 UTC, Averimon requested changes
Please fix merge conflicts

2025-02-18 10:25 UTC, flowmdev requested changes
Script looks very reasonable. Though I can't look through all the prefab / scene file changes, I strongly believe that you did your work well 👍🏼

I tested out the functionality and it seems that some files still update upon resaving. Maybe this should be done once more (and pushed) before merging the PR.

2025-02-19 08:49 UTC, FlorianGlawogger commented
@Averimon I merged the branch again, and reran the script, a few files were changed, but not many.

Note that files only containing line ending changes might show up as changed files if you type `git status`. 
Additionally, floating point precision errors also result in changes (afaik we are not able to prevent those otherwise please let me know. (e.g. if you open a scene, move a GameObject in the hierarchy, move it back to its original position, then it is possible some floating point values changed very slightly, e.g:
```
      value: 354.93225
```
becomes
```
      value: 354.936
```

If you notice any other changes upon resaving please let me know, then I'll try to tackle those as well!

2025-02-19 13:07 UTC, Averimon approved these changes
Thanks for the clarification! Either way, it looks very nice now. Should be good to merge 😄

2025-02-19 13:07 UTC, merged